### ISSUE TITLE
Idempotency of Web Service Server Connection URI

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/ibmsecurity#105]
Observed behavior (9.0.4) / Web Service URI (mga/server_connections/ws)

I am testing a cURL command to isolate an observed behavior for a role I am trying to develop:

curl -k --user someuser:somepassword -H "Content-Type:application/json" -H "Accept: application/json" -X PUT -d '{"connection":{"url":"someuri","user":"easuser","ssl":true,"sslTruststore":"localCAs.kdb","sslAuthKey":"service-key"},"type":"ws","name":"some-endpoint-name","description":"some description","uuid":"a940412f-0214-4629-919a-5213508c90fe","locked":false}' https://someserver/mga/server_connections/ws/{a940412f-0214-4629-919a-5213508c90fe}/v1
{"connection":{"url":"someuri","user":"easuser","ssl":true,"sslTruststore":"localCAs.kdb","sslAuthKey":"service-key"},"type":"ws","name":"some-endpoint-name","description":"some description","uuid":"a940412f-0214-4629-919a-5213508c90fe","locked":false}

for which I get a HTTP 200 response each time I call it.

When I look at LMI, there is a pending change but values did not change. I accept to commit in LMI to and retry and I get again a pending change in LMI as a result with the same URI/JSON submitted.

Do you know if there is special about this URI ?

Does the fact that this connection object contains a password would make it impossible to not update itself on every cURL PUT ?

Restarting the AAC Runtime between 2 cURL identical cmd does not help.

**Comment by ram-ibm** [comment]
I have not used this REST API yet - so not sure whats happening. I do know that making a PUT call even if there are no changes will cause pending changes to appear. Also passwords do get obfuscated and are not always returned for idempotency check.

Have you tried it from the LMI and run a trace?

**Comment by sygilber** [comment]
Make sense. I should have focus less on why the HTTP PUT generates pending changes (which is normal) and instead focus on why the current update() methods in server_connection do not perform comparison of new and old values, which is the real cause for HTTP PUT always sent to the appliance (just found out after your explanation). While i am making the update() methods work, i will make sure that comparison is introduced in the methods as well.

**Comment by sygilber** [comment]
Comments provided did the trick to put me back on the right track. Thanks
