### ISSUE TITLE
9.0.5 compatibility

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/ibmsecurity#111]
Starting to experiment running our sets of playbooks for 9.0.4 agains 9.0.5 and already we can spot some items (admin_cfg) that require a bit of work to ensure proper behavior is achieve (idempotency just to name that one).

Will begin fixing issues as they come up and will submit a pull request once we have resolve pretty much all issues that come up for our playbooks.

**Comment by Eskotus** [comment]
I don't know if it's 9.0.5 related, but seems like ...cluster.node.add fails to get_id returning 404. It can be worked around with force=True, but maybe the response handling could be improved.

**Comment by sygilber** [comment]
I’ve pushed pull request already earlier in early August and the PR is still pending for review and merge.

**Comment by sygilber** [comment]
Hello Eskotus,

I just noticed your post from Septembre 13th. 

Actually, i have noticed myself it also with 9.0.4 back in January 2018 this behavior, and my only workaround at the time was to re-run that pay a second time.

So from what I hear from you is that this behavior is still present in 9.0.5 ? If so I will pay more attention the next time I roll out ne 9.0.5 and configure clustering. I have more experience now with the ibmsecurity stack, I could try to trace where/why it is failing.

**Comment by sygilber** [comment]
Issues raised originaly in this item are now resolved with https://github.com/IBM-Security/ibmsecurity/pull/115

Thanks
