### ISSUE TITLE
Unable to apply ipv4 addresses on the same subnet to multiple interfaces 

### ISSUE THREAD

**Issue by Mistrblank** [IBM-Security/ibmsecurity#116]
We have two interfaces on a single ISAM VM that when configured are on the same subnet. 
We're using the ansible roles to manage configuration. 

ibmsecurity.isam.base.network.interfaces_ipv4.update won't update the second interface and 
ibmsecurity.isam.base.network.interfaces_ipv4.add won't add.  

Update functionality just does nothing and comes back "ok".  However attempting to add delivers this error:
fatal: [isam-host]: FAILED! => {"changed": false, "log": "[2018-09-13 14:21:20,506] [PID:15440 TID:139861666948928] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieving version ***\n[2018-09-13 14:21:40,652] [PID:15440 TID:139861666948928] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Get Setup Complete Settings ***\n[2018-09-13 14:21:40,769] [PID:15440 TID:139861666948928] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieving activations ***\n[2018-09-13 14:21:40,885] [PID:15440 TID:139861666948928] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieving all interfaces ***\n[2018-09-13 14:21:41,014] [PID:15440 TID:139861666948928] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Updating a (VLAN) interface ***\n[2018-09-13 14:21:41,151] [PID:15440 TID:139861666948928] [ERROR] [ibmsecurity.appliance.ibmappliance] [_process_response():46]   Request failed: \n[2018-09-13 14:21:41,151] [PID:15440 TID:139861666948928] [ERROR] [ibmsecurity.appliance.ibmappliance] [_process_response():47]      status code: 400\n[2018-09-13 14:21:41,152] [PID:15440 TID:139861666948928] [ERROR] [ibmsecurity.appliance.ibmappliance] [_process_response():49]      text: {\"error\":\"Address 192.168.0.65/255.255.255.0 overlaps a subnet on interface 1.1 This interface will not be able to be updated until all overlapping IPv4 addresses are removed.\"}\n", "msg": "('HTTP Return code: 400', u'{\"error\":\"Address 192.168.0.65/255.255.255.0 overlaps a subnet on interface 1.1 This interface will not be able to be updated until all overlapping IPv4 addresses are removed.\"}')", "name": "ibmsecurity.isam.base.network.interfaces_ipv4.add"}

Yet we have this exact configuration running elsewhere and the Web GUI and command line allow this.

**Comment by Mistrblank** [comment]
There's an overrideSubnetChecking.  

Lack of full documentation wish examples hurts

**Comment by ram-ibm** [comment]
The python code uses the same variable names as that in the REST API Documentation. But I agree not having examples is a problem. Will add this to our list of things to do. Please feel free to open issues if stuck for now. Thanks.
