### ISSUE TITLE
new parameter extProperties should be added in aac/api_protection/clients.py for ISAM 9.0.5

### ISSUE THREAD

**Issue by bjsong19** [IBM-Security/ibmsecurity#119]
in ISAM 9.0.5, API Protection Clients definition have a new tab to add extra client information as a JSON Array object. its RAPI parameter is extProperties should be added in clients.py definition for add, update and set functions.

**Comment by sygilber** [comment]
Hi, i have some change ready pending in this PR for your request: 
https://github.com/IBM-Security/ibmsecurity/pull/115

Will re-check with Ram soon how to deal with this.

**Comment by sygilber** [comment]
Hi, the #115 has been merged now for some time. Can you please validate with the new code and close this issue if all is good on your end ?

Thanks
