### ISSUE TITLE
No stop/start/restart functionality for authorization servers

### ISSUE THREAD

**Issue by Mistrblank** [IBM-Security/ibmsecurity#126]
The documentation for it is hosted on the server instances at: 
https://HOSTNAME/doc/RAPI/Stopping,%20starting,%20or%20restarting%20an%20authorization%20server%20instance.xml
(Replacing hostname with your isam server hostname)...

Functionality is needed consequently in Ansible, required as we're experiencing a memory leak in the auth server and need to schedule regular restarts.

**Comment by ram-ibm** [comment]
The python code is already developed. ibmsecurity.isam.web.authorization_server.instance.execute(). You can clone rp_operation.yml sample playbook and create one called as_operation.yml and leverage python code that way. You will need a role as well.

What do you need help with please?

**Comment by Mistrblank** [comment]
Ok, I missed execute(), but where is rp_operation.yml?   I just searched the isam-ansible-roles and I don't see it.

**Comment by Franclaf7** [comment]
It's a playbook. Here you go:

https://github.com/IBM-Security/isam-ansible-playbook-sample/blob/master/rp_operation.yml
