### ISSUE TITLE
ibmsecurity won't work with python 3.7.2 or python 3.x due to depricated user module

### ISSUE THREAD

**Issue by juttlaing** [IBM-Security/ibmsecurity#135]
The main page states ibmsecurity requires python 2.7.10 or HIGHER.  However I noticed ibmsecurity won't run with python 3.x at all.  This is because python module "user" was depricated in python 2.6 and was removed from python 3.x all together.

During loading of the ibmsecuriy modules, \ibmsecurity-master\ibmsecurity\user\isamuser.py in lin2 tries to load module "user".  Yet the module doesn't exist.  It runs fine in python 2.7.14 but not python 3.x due to this depricated module.

Are there any plans on making this code work with Python 3.x?

Is there anything I can do to rig python 3.x to work with ibmsecurity?

`F:\Automation\scripts\ibmsecurity-master>python --version
Python 3.7.2

F:\Automation\scripts\ibmsecurity-master>testisam.py
Traceback (most recent call last):
  File "F:\Automation\scripts\ibmsecurity-master\testisam.py", line 5, in <module>
    from ibmsecurity.user.isamuser import ISAMUser
  File "F:\Automation\scripts\ibmsecurity-master\ibmsecurity\user\isamuser.py", line 2, in <module>
    from user import User
ModuleNotFoundError: No module named 'user'`

**Comment by mlu-ibm** [comment]
Python 2.x and 3.x are incompatible, Python 2.x or above does not mean it can support the incompatible Python 3.x. Python 2.x will be supported at least till 2020. 

To make the code compatible for both 2.x and 3.x require some work, we need to review the code and size the efforts. Or we may create a new repository for Python 3.x only code.

**Comment by ram-ibm** [comment]
I did some preliminary work to check how to make the code compatible with both Python 2.x and 3.x - looks possible just need to execute on it.

FYI Ansible did not support Python 3.x till recently. When we created this we stayed within the boundaries of what Ansible would support, which was Paython 2.x.

**Comment by juttlaing** [comment]
Hey – that’s great.  First – excellent work.  I’ve been using ibmsecurity for over a year both with ansible and with my own python scripts which have automated many tasks for the ISAM team here at my firm.  So kudos!

Please keep us up to date when the code will work with python 3.  Soon our firm will no longer allow Python 2.7, and ibmsecurity is vital.  Appreciate all you do!​​​​​


Jutt Laing
Manager Access Management, KTech Sec Pro TechOp
KPMG LLP | 75 Chestnut Ridge Rd | Montvale, NJ 07677
office: +1 (201) 949-2898 | mobile: +1 (484) 653-8561 | juttlaing@kpmg.com<mailto:juttlaing@kpmg.com>
____________________

KTech will empower our firm’s success through technology innovation, productivity, security and operational excellence.

Please consider the environment before printing.

**Comment by ram-ibm** [comment]
FYI - the particular problem you encountered looks to be a typo. We have a local User class and are not using the deprecated module.

from .user import User

Missing "." to indicate local directory.

**Comment by ram-ibm** [comment]
I fixed the user import. Closing this for now.
