### ISSUE TITLE
Release to PyPi

### ISSUE THREAD

**Issue by jobec** [IBM-Security/ibmsecurity#150]
* Switch to normal semver versioning
* Create release tags on github
* Release packages on PyPi

This allows people to use this package in a standard pythonic way which is a big advantage for those not so experienced with Python in general.

Installing straight from github without any release tags will eventually lead to issues like:
* Breaking all users their code if big changes are made
* Or the other way aound: preventing major improvements in the future because it would break people's code

**Comment by ram-ibm** [comment]
I had looked to figure out which versioning will work best, I think date based versioning is still the best options compared with semantic versioning. Especially since we support more than one product (ISDS and ISAM for now) within the package.

Ideally we should push to PyPI - that option has been explored. We just need to prioritize to make it happen.

Yes - the current setup is not ideal and certainly PyPI will make it easier.

**Comment by jobec** [comment]
There's no reason why you wouldn't be able to use semantic versioning when supporting 2 products.

**Comment by ram-ibm** [comment]
I personally do not see any value between use semantic versioning versus the current timestamp based approach. The key for you is that it is continuously "increasing".

Timestamp based approach at least gives me the information around what timeframe the package was updated. Semantic would not correlate to any meaningful information.

I suspect that this could be argued both ways - but for now I am going to leave the versioning system as-is.

However, I agree with publishing to PyPI and am exploring how to make it happen.

**Comment by jobec** [comment]
Calver makes it impossible to do version pinning.

You can't say `<3.0.0` for example to prevent breaking changes from sneaking in yet follow patch updates, when you're on 2.4.6 for example.

If the API version of an ISAM appliance was ever to change and you need to make backwards incompatible changes, Calver will break your release cycles.

To see when a package is update you can always use git, pypi, release notes...

Anyway, you're the maintainer and can do what you want. I can only say what experience told me.

**Comment by ram-ibm** [comment]
I don't have to right, open to doing the right thing :-)

I was under the impression calver allows you do the exact same - I can do <2019.05.22.0. What am I missing please?

**Comment by jobec** [comment]
imagine this situation:
* I want to pin to a release where I get patch updates, but never breaking changes
* I pinned to version <2020.0.0
* On 2019.11.2 you make a breaking change
* my code melts...

Or,

* I want to pin to a release where I get patch updates, but never breaking changes
* I pinned to version <2020.0.0
* On 2020.1.1 you make a patch update
* my code never receives the patch updates

Also, with every new release, I now need to go through the release notes and scan for breaking changes. With semver, I just know when you’ll make a breaking change.

From semver.org :
> Given a version number MAJOR.MINOR.PATCH, increment the:
>
> * MAJOR version when you make incompatible API changes,
> * MINOR version when you add functionality in a backwards-compatible manner, and
> * PATCH version when you make backwards-compatible bug fixes.

**Comment by ram-ibm** [comment]
Okay now I see what you are driving at. The framework basically is dependent on the appliance REST APIs for what is backward compatible versus not. We do not intend to break any existing logic for now - but it has happened (runtime_template as an example).

One option is to be more careful so we do not break any existing logic out there. So we don't have to manage versioning to indicate that to be happening. Will evaluate and re-visit this topic please. Thanks.

**Comment by ram-ibm** [comment]
Code has been uploaded to PyPi. Please note that at this time we are continuing with versioning based on calendar dates. Will re-visit when there is more reason to change the versioning strategy. Thanks.
