### ISSUE TITLE
Adding static route on missing interface makes playbook crash

### ISSUE THREAD

**Issue by Franclaf7** [IBM-Security/ibmsecurity#153]
If one mistakenly tries adding a static route to a non-existing Interface, the playbook returns this error:

> Error> action does not have the right set of arguments or there is a code bug!

The error didn't make any sense at first. We checked all of our "add_static_route" role parameters and everything was fine. We then tracked it back up to the missing interface. 

Just like issue #122, there will be a similar proposed fix in a PR.

**Comment by ram-ibm** [comment]
This was one of the first code to be developed - at that time there was no concept of warning in the framework. It would be best to return a warning for sure.

**Comment by Franclaf7** [comment]
Resolved by #154

Closing
