### ISSUE TITLE
set() method in ibmsecurity/isam/docker/service_configuration/configuration.py missing force&check_mode arguments?

### ISSUE THREAD

**Issue by njk2019** [IBM-Security/ibmsecurity#159]
Hi,

I am testing my custom Ansible role that is using the following ibmsecurity action: ibmsecurity.isam.docker.service_configuration.configuration.set.

I was getting the following error before adding the " check_mode=False, force=False" arguments to the set() method:

Error> action does not have the right set of arguments or there is a code bug! Options: isamAppliance=isam_server, force=False, hvdb_password=\"Passw0rd\", hvdb_db_type=\"postgresql\", hvdb_port=\"5432\", hvdb_db2_alt_address=\"\", hvdb_address=\"iamlab-isampostgresql\", hvdb_user=\"postgres\", hvdb_db2_alt_port=\"\", hvdb_db_secure=False, hvdb_driver_type=\"thin\", hvdb_db_name=\"isam\"", "name": "ibmsecurity.isam.docker.service_configuration.configuration.set"}

**Comment by ram-ibm** [comment]
Yes it is missing check_mode and force flags. Will update and let you know when it is fixed.

**Comment by djorgen-ibm** [comment]
This issue has been fixed.
