### ISSUE TITLE
Bug in the set() method of ibmsecurity/isam/base/dsc.py

### ISSUE THREAD

**Issue by njk2019** [IBM-Security/ibmsecurity#160]
On line 36 of https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/base/dsc.py there is a call to _check() method:

  if force is True or _check(isamAppliance, dsc_json) is False:

This causes an error because _check() needs 3 arguments.

**Comment by ram-ibm** [comment]
I am working on this module - made changes, but have not had a chance to test before pushing.

**Comment by ram-ibm** [comment]
Wondering if I should push the changes without testing it - depends on the urgency of your need? I am a bit pressed into getting my docker environment up for testing.

**Comment by njk2019** [comment]
Suits me. Here's my diff

diff --git a/ibmsecurity/isam/base/dsc.py b/ibmsecurity/isam/base/dsc.py
index 66486ed..2d797ca 100644
--- a/ibmsecurity/isam/base/dsc.py
+++ b/ibmsecurity/isam/base/dsc.py
@@ -33,7 +33,7 @@ def set(isamAppliance, service_port=443, replication_port=444, worker_threads=64
     if servers is not None:
         dsc_json["servers"] = servers

-    if force is True or _check(isamAppliance, dsc_json) is False:
+    if force is True or _check(isamAppliance, dsc_json, False) is False:
         if check_mode is True:
             return isamAppliance.create_return_object(changed=True, warnings=warnings)
         else:

**Comment by ram-ibm** [comment]
This should be fixed for now - will re-visit logic to allow for idempotency ignoring password.
