### ISSUE TITLE
ISDS available_updates.py bug

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/ibmsecurity#166]
ibmsecurity/ibmsecurity/isds/available_updates.py

Trying to apply ISDS firmware 8.0.1.10 over ISDS 8.0.1.9 and getting this log entry which explains why the firmware installation skips:

`[INFO] [ibmsecurity.isds.available_updates] [_check_file():77] Active partition has version 8.0.1.9-ISS-ISDS_20181207-0045 which is greater or equals install package at version 8.0.1.10-ISS-ISDS_20190223-0443`

There is obviously somewhere in the following code a bug: 

```
        for firm in ret_obj['data']:
            if firm['active'] is True and firm['name'] >= fn[0]:
                logger.info(
                    "Active partition has version {0} which is greater or equals install package at version {1}.".format(
                        firm['name'], fn[0]))
                return True
```

Will try to get this resolve. 

I cannot exclude that it exists also in the same python code for ISAM as the code is exactly the same, but for ISAM, the firmware version number have not reached this pattern yet.

**Comment by sygilber** [comment]
In Python:

if "8.0.1.9-ISS-ISDS_20181207-0045" > "8.0.1.10-ISS-ISDS_20190223-0443":
    print("1")
else:
    print("2")

Gives "1"

So we need to switch to something else for version comparison, either external package or some cheap and dirty version comparator that we can code and add directly in ibmsecurity.

Any thoughs ?

**Comment by ram-ibm** [comment]
tools has a version_compare() -- perhaps extract version from file and compare?

**Comment by sygilber** [comment]
Hi Ram

We are likely needing to update version_compare() method as it throws data error when running this code snippet:

> assert version_compare("8.0.1.10-ISS-ISDS_20181207-0045", "8.0.1.9-ISS-ISDS_20181207-0045") > 0

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/sygilber/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/utilities/tools.py", line 279, in version_compare_unit_test
>     assert version_compare("8.0.1.10-ISS-ISDS_20181207-0045", "8.0.1.9-ISS-ISDS_20181207-0045") > 0
>   File "/home/sygilber/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/utilities/tools.py", line 253, in version_compare
>     if normalize(version1) == normalize(version2):
>   File "/home/sygilber/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/utilities/tools.py", line 251, in normalize
>     return [int(x) for x in re.sub(r'(\.0+)*$', '', v).split(".")]
> ValueError: invalid literal for int() with base 10: '10-ISS-ISDS_20181207-0045'

Similiarly, for version of type ISAM, getting the following fatal errror:

> assert version_compare("isam_9.0.10.0_20161102-2353", "isam_9.0.2.0_20161102-2353") > 0

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/sygilber/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/utilities/tools.py", line 279, in version_compare_unit_test
>     assert version_compare("isam_9.0.10.0_20161102-2353", "isam_9.0.2.0_20161102-2353") > 0
>   File "/home/sygilber/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/utilities/tools.py", line 253, in version_compare
>     if normalize(version1) == normalize(version2):
>   File "/home/sygilber/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/utilities/tools.py", line 251, in normalize
>     return [int(x) for x in re.sub(r'(\.0+)*$', '', v).split(".")]
> ValueError: invalid literal for int() with base 10: 'isam_9'


My initial assessment is that the this method is expecting only numerical values which I just found confirmed/documented already in the code:

> def version_compare(version1, version2):
>     """
>     Compare two ISAM version strings. Please note that the versions should be all numeric separated by dots.

We have several options:

a) We propose a new function (version_compare_firmware()) in tools.py that will support an extended version of the version_compare() that will support non-numerical values (but that will be stripping everything that is not numeric or dots before using the original version_compare() ).

b) Wherever in ISAM or ISDS code where one needs to use version_compare(), caller must ensure first to extract the numerical dotted version substring from the complete firmware name before passing it to the unmodified version_compare(). If that is to be performed in many places, then this is not optimal.  

The way I see this, this is truly only needed when we are extracting the firmware name of a target appliance and comparing it to the file name of a local PKG file, more likely during the processing of applying firmware updates.

In any event, one question raises above all other consideration: are we accepting the fact that there should never be numerous build/date number for the same firmware floating around? Or the opposite .... we would need to assume that for a given firmware target release say 9.0.1.20 ... there could be numerous build number ... (alpha, beta, ...) before an official GA is released? Here I am not even concerned with the fact that IBM would probably never support an Appliance of Beta code level being updated to a GA package file level.

Thanks for comments.

**Comment by sygilber** [comment]
In the end, because the PKG file format is not similar for ISDS and ISAM, and because the code under ibmsecurity.utilities is meant to be as much as possible product agnostic (isam vs isds vs ...) I did not want to introduce in the tools.py module product specific intricacies.
So the solution was to extract the production version number first from PKG files before passing it to the tools.version_compare() generic method.

The fix for available_updates.py of both ISDS and ISAM is found under the following PR:

https://github.com/IBM-Security/ibmsecurity/pull/188

**Comment by sygilber** [comment]
Resolved by https://github.com/IBM-Security/ibmsecurity/pull/188/files
