### ISSUE TITLE
import_zip file action throwing invalid zip file 

### ISSUE THREAD

**Issue by qfitsoln** [IBM-Security/ibmsecurity#167]
Hi Team,

 We have executed import-managemnt-root with the help of import_zip file as part of import_management_root_zip_filename param  but its saying invalid zip file. 

Could you please help us  on uploading the zip file to isam by using action.

action: ibmsecurity.isam.web.reverse_proxy.management_root.all.import_zip
    isamapi:
      instance_id: "{{ update_management_root_instance_id }}"
      filename : "{{ update_management_root_zip_filename }}"

**Comment by ram-ibm** [comment]
Please extract a zip file using LMI - and then use that as a template for your upload.

**Comment by ri2903** [comment]
I did not understand when you said extract zip file using LMI , could you please elaborate and our web dev team gives the login package as a zip and please do suggest us some better idea how we could deploy it using ansible in ISAM , can't we just specify a zip and deploy it as ansible and ISAM will take care of it  ?

**Comment by ram-ibm** [comment]
The zip file needs to have the right directory structure. You can extract a file from appliance to figure out what that needs to look like.

**Comment by ram-ibm** [comment]
Looks like the URI has a bug - I am testing to make sure there is no other issue. Will provide a code fix asap.

**Comment by ram-ibm** [comment]
Please confirm that you are not mixing these two functions up:
ibmsecurity.isam.web.reverse_proxy.management_root.all.import_zip()
and
ibmsecurity.isam.web.reverse_proxy.instance.import_config()

Which zip file are you looking to import?

**Comment by ri2903** [comment]
Junction root zip file we are trying to deploy and Junction root i have has html file css file and gif files png files,jpg files as well ,these are file format that we are trying to deploy and apart from that the sample directory we want is directory inside directory and inside that directory a file of above mentioned formats for example

**Comment by ri2903** [comment]
Dev team gives the Junction root like below example , i am trying to deploy via ansible,could you please give suggestions on this how to proceed with this


Example 
Directory
——-> Directory
                     ———-> file (html,jpg,gif,css,png,txt)
———> Directory
                     ———-> file (html,jpg,gif,css,txt,png)

**Comment by ram-ibm** [comment]
Use the LMI (Local Management Interface) or the Browser based WEB GUI to connect to the appliance. Upload the files as required by your dev team. Then extract the zip file using the LMI and import it using the ansible function.

Be aware for the reverse proxy there are two kinds of zip files that you can extract - one includes all configs, junctions, management root, etc. The other is only management root. The latter is what you need, or so I believe based on your description. The corresponding python function for it is "ibmsecurity.isam.web.reverse_proxy.management_root.all.import_zip()".

**Comment by ri2903** [comment]
I did not understand this “ Then extract the zip file using LMI and import it using the ansible function and also we are just trying to deploy a login package which consists of html css jpg gif and png file and it is only deploying html files
Could you please help us on this or if possible create a role where it could take a zip file of any format and deploy it in ISAM instance ?

**Comment by ram-ibm** [comment]
"zip file of any format" - the framework is designed to handle only those zip files that the REST APIs themselves can handle. So if you do not match what is required then it is upto you to massage it. I dont know how to design to role to handle any arbitrary zip file.

You refer to a login "package" - I suspect that you may need to load the login.html and then the css/gif and such in the junction-root folder.

Here are detailed steps:
Login to ISAM appliance using a browser
Secure Web Settings -> Manage -> Reverse Proxy
Select your reverse proxy
Manage -> Management Root 
Select the folder (expand as necessary) and use Manage -> Import to add files
After you ensure that the appliance has all necessary files then Manage -> Export zip

Use this zip file in an ansible role to configure other servers, or you can edit the zip file for future enhancements.

**Comment by ri2903** [comment]
The zip i am referring here junction root zip itself and we are trying to upload it across the servers and i am having trouble while doing with ansible as it is only deploying html files not any other please help me understand

**Comment by ram-ibm** [comment]
I suspect that you are not understanding how ISAM requires particular types of zip files for each REST API. You really need to get on an ISAM appliance and try it out using the browser interface before replicating it in Ansible.
