### ISSUE TITLE
aac/server_connections/ldap.py throws id error on update

### ISSUE THREAD

**Issue by babl-timandrews** [IBM-Security/ibmsecurity#169]
Update via Ansible on LDAP server_connection in AAC throws a 404 due to the ID not being requested under the update function:

 return isamAppliance.invoke_put(
            "Modifying an LDAP server connection",
"/mga/server_connections/ldap/{0}/v1".format(id), json_data)

"PUT /mga/server_connections/ldap/%3Cbuilt-in%20function%20id%3E/v1 HTTP/1.1\" 404 None

Just needs the following added like in the delete function:
ret_obj = _get_id(isamAppliance, name=name)
id = ret_obj['data']

**Comment by babl-timandrews** [comment]
[errortrace.txt](https://github.com/IBM-Security/ibmsecurity/files/3458794/errortrace.txt)

**Comment by babl-timandrews** [comment]
Analysing the code, looks like smtp.py has the same issues in both update and delete functions.

**Comment by ram-ibm** [comment]
Please note that we are cleaning up the code base for server connections. Please see latest merge request.

**Comment by ram-ibm** [comment]
Could you test and confirm the latest code merge has fixed your problem and close this issue please? Thanks.

**Comment by babl-timandrews** [comment]
Confirmed, not idempotent, but does fix the issue I was having.
