### ISSUE TITLE
Inconsistency between junctions.delete and junctions_server.delete URL

### ISSUE THREAD

**Issue by 0bscur3** [IBM-Security/ibmsecurity#17]
Can we please change the `...junction_id=/` to `...junction_id=` in [junctions_servers.delete](https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/web/reverse_proxy/junctions_server.py#L118) to match the [junctions.delete](https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/web/reverse_proxy/junctions.py#L258) action? This inconsistency breaks my inventory.

**Comment by 0bscur3** [comment]
This is also addressed in my pull request #18

**Comment by ram-ibm** [comment]
I merged the changes. Thanks for catching these!
