### ISSUE TITLE
0804 - MR has basestring issue

### ISSUE THREAD

**Issue by Scoi4101** [IBM-Security/ibmsecurity#170]
ansible-playbook 2.8.2
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

As soon as the framework loads

TASK [set_junction : Update a Junction - *BLAH*] **********************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name basestring
fatal: [CIAISAPP0163.sys.cigna.com]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 114, in <module>\n  File \"<stdin>\", line 106, in _ansiballz_main\n  File \"<stdin>\", line 49, in invoke_module\n  File \"/tmp/ansible_isam_payload_0i66UE/__main__.py\", line 11, in <module>\n  File \"/usr/lib/python2.7/site-packages/ibmsecurity/appliance/isamappliance.py\", line 9, in <module>\n    from ibmsecurity.utilities.tools import basestring\nImportError: cannot import name basestring\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by kurt-green** [comment]
We see the same.. looks like the last changes are a force update to python 3.

**Comment by ram-ibm** [comment]
Please use version 2019.8.4.1 instead, the issue seems to with python2 with 2019.8.4.2. A fix is coming.

**Comment by ram-ibm** [comment]
2019.8.6.0 has the fix for this issue.
