### ISSUE TITLE
Import error:No module named ‘requests.packages.urllib3.exceptions’

### ISSUE THREAD

**Issue by ri2903** [IBM-Security/ibmsecurity#175]
Hi i am trying to complete update reverse proxy conf role and i am getting this error what should i do could you please help me 

ImportError:No module named ‘requests.packages.urllib3.exception’

**Comment by ram-ibm** [comment]
You need to install/setup your environment properly. I quick search should get you plenty of answers.

**Comment by ri2903** [comment]
Thank you Ram for your help i will be reconfiguring it again
