### ISSUE TITLE
ISAM VERSION ISSUE IN PROCESS.PY

### ISSUE THREAD

**Issue by ri2903** [IBM-Security/ibmsecurity#182]
Could you please update the process.py from 9.0.2.0 to 9.0.7.0 as we are at isam 9.0.7.0 as we are trying to restart AAC and it is not happening even though the playbook is executed.

def execute(isamAppliance, operation="restart", check_mode=False, force=False):
    """
    Execute an operation (start, stop or restart) on runtime
    """
    warnings = []
    # Reload function is new to ISAM v9.0.2.0
    if operation == "reload" and tools.version_compare(isamAppliance.facts["version"], "9.0.2.0") < 0:
        warnings.append(
            "Appliance is at version {0}, reload requires atleast v9.0.2.0".format(isamAppliance.facts['version']))
        return isamAppliance.create_return_object(warnings=warnings)

    if force is True or _check(isamAppliance, operation) is True:
        if check_mode is True:
            return isamAppliance.create_return_object(changed=True, warnings=warnings)
        else:
            return isamAppliance.invoke_put(
                "Executing an operation on runtime", uri,
                {
                    'operation': operation
                }, requires_modules=requires_modules, requires_version=requires_version, warnings=warnings)

    return isamAppliance.create_return_object()

**Comment by ram-ibm** [comment]
What is the output? The code checks to see if a restart is needed before it does it. Maybe you need to force restart if it is not labelled as needing one.

The version check you are seeing in the posted code is ensuring that you are at the right level to leverage that capability.

**Comment by ri2903** [comment]
The playbook ran successful however restart is not happening since we are using 9.0.7.0 it is not recognizing the isam appliance since it is looking for isam appliance 9.0.2.0
Could you please change the version to 9.0.7.0 in the code so that restart would happen

**Comment by ri2903** [comment]
“The version check you are seeing in the posted code is ensuring that you are at the right level to leverage that capability” 

But i think because of this check it is not restarting the AAC and it is just running the playbook successfully however the isam appliance with 9.0.7.0 version it is not recognizing and restart is not happening

Could you also please suggest me how to force the restart as you have suggested previously.

**Comment by ram-ibm** [comment]
It is difficult to teach both ISAM and Ansible through this medium. Suggest other alternatives.

--> You can pass a variable force=True to the -e option of ansible-playbook. This overrides the idempotency check and forces the code to do regardless of current state.

--> Look at the runtime and see if it *requires* a restart. Idempotency check explicitly sees if a restart is required before it does it.
