### ISSUE TITLE
Issue with entries in ibmsecurity.isam.web.reverse_proxy.configuration.entry.set

### ISSUE THREAD

**Issue by toonvdn** [IBM-Security/ibmsecurity#189]
Hello,

There seems to be an issue with this method with regards to the "entries" argument.

The value I'm using is not allowed for:
ibmsecurity.isam.web.reverse_proxy.configuration.entry.set
but is allowed for:
ibmsecurity.isam.web.reverse_proxy.configuration.entry.add

This is the error that is generated:

```
"msg": "Traceback (most recent call last):
  File \"/tmp/ansible_isam_payload_gwHqX9/__main__.py\", line 128, in main
    ret_obj = eval(func_call)
  File \"<string>\", line 1, in <module>
  File \"/usr/lib/python2.7/site-packages/ibmsecurity-2019.08.09.0-py2.7.egg/ibmsecurity/isam/web/reverse_proxy/configuration/entry.py\", line 124, in set
    return _add(isamAppliance, reverseproxy_id, stanza_id, set_entries)
  File \"/usr/lib/python2.7/site-packages/ibmsecurity-2019.08.09.0-py2.7.egg/ibmsecurity/isam/web/reverse_proxy/configuration/entry.py\", line 78, in _add
    {\"entries\": entries})
  File \"/usr/lib/python2.7/site-packages/ibmsecurity-2019.08.09.0-py2.7.egg/ibmsecurity/appliance/isamappliance.py\", line 366, in invoke_post
    warnings=warnings)
  File \"/usr/lib/python2.7/site-packages/ibmsecurity-2019.08.09.0-py2.7.egg/ibmsecurity/appliance/isamappliance.py\", line 336, in _invoke_request
    self._process_response(return_obj=return_obj, http_response=r, ignore_error=ignore_error)
  File \"/usr/lib/python2.7/site-packages/ibmsecurity-2019.08.09.0-py2.7.egg/ibmsecurity/appliance/isamappliance.py\", line 66, in _process_response
    raise IBMError(\"HTTP Return code: {0}\".format(http_response.status_code), http_response.text)
IBMError: ('HTTP Return code: 400', u'{\"message\":\"A required parameter is missing : entries\"}')
  
 isamAppliance=isam_server, force=True, reverseproxy_id=\"my_reverse_proxy\", stanza_id=\"mmfa-config-info\", entries=[['autoconfig', 'mmfa']]",
```

What could be the cause of this?

Kind regards,
Toon

**Comment by sygilber** [comment]
Hi

I have posted a PR on September 4th to resolve this issue which is still pending for review. 

In the mean time, you could always try testing the fix on your end while it is pending for merge ?

Cheers

**Comment by sygilber** [comment]
Hi @toonvdn, please have a look if the latest PR merged last night resolved the behavior you have reported.

**Comment by sygilber** [comment]
Hi again, is the latest commits resolve this reported issue for you ? If not, please let us know, If yes, really appreciated if you could close the issue. Thanks

**Comment by toonvdn** [comment]
Still receive errors as shown underneath.
Using latest version.

`{
    "_ansible_parsed": true,
    "changed": false,
    "_ansible_no_log": false,
    "_ansible_item_result": true,
    "name": "ibmsecurity.isam.web.reverse_proxy.configuration.entry.set",
    "item": {
        "key": "mmfa-config-info",
        "value": {
            "entries": [
                [
                    "autoconfig",
                    "mmfa"
                ]
            ]
        }
    },
    "log": "[2019-11-27 12:47:01,465] [PID:98 TID:140397418731328] [ERROR] [ibmsecurity.appliance.ibmappliance] [_process_response():64]      text: {\"message\":\"A required parameter is missing : entries\"}\n",
    "invocation": {
        "module_args": {
            "username": "xxxxxx",
            "adminProxyProtocol": "https",
            "adminProxyHostname": null,
            "force": true,
            "log": "INFO",
            "adminProxyPort": 443,
            "appliance": "xxxxxx",
            "adminProxyApplianceShortName": false,
            "lmi_port": 443,
            "isamapi": {
                "reverseproxy_id": "xxxxxx",
                "stanza_id": "mmfa-config-info",
                "entries": {
                    "entries": [
                        [
                            "autoconfig",
                            "mmfa"
                        ]
                    ]
                }
            },
            "action": "ibmsecurity.isam.web.reverse_proxy.configuration.entry.set",
            "omitAdminProxy": false,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "msg": "('HTTP Return code: 400', u'{\"message\":\"A required parameter is missing : entries\"}')",
    "_ansible_ignore_errors": null,
    "_ansible_item_label": {
        "key": "mmfa-config-info",
        "value": {
            "entries": [
                [
                    "autoconfig",
                    "mmfa"
                ]
            ]
        }
    }
}`

What is wrong?

**Comment by sygilber** [comment]
Hi 

So the "http 400" at least tells us this is the Virtual Appliance not liking what we provided. I've never used this particular stanza "mmfa-config-info".  Could you please share your Ansible playbook/role code snipet you are using ? This is just to allow me to on-board myself on troubleshooter this faster in my environment.

In the mean time, this is what I've tested assuming you are using Ansible roles:

>     - role: set_reverseproxy_conf
>       set_reverseproxy_conf_entries:
>         - { stanza_id: "mmfa-config-info", entries: "[['autoconfig','mmfa']]" }

Which resulted in the following task execution status:

> TASK [set_reverseproxy_conf : Set values into Reverse Proxy Configuration File] *************************************************************************************************************************************************************
> changed: [someservert] => (item={u'stanza_id': u'mmfa-config-info', u'entries': u"[['autoconfig','mmfa']]"})
> 

Resulted in the following entries added to WebSEAL configuration and it restarted successfully:

> [mmfa-config-info]
> autoconfig = mmfa
> 

I just reconfirmed that I was using the lastest master branch of python code.

>         "ansible 2.8.4",
>         "ibmsecurity Version: 2019.11.19.0",

**Comment by toonvdn** [comment]
Hello,

This is the code to invoke the configuration update:

```
    - name: Configure Reverse Proxy
      isam:
        appliance: "{{ inventory_hostname }}"
        username:  "{{ username }}"
        password:  "{{ password }}"
        lmi_port:  "{{ lmi_port }}"
        log:       "{{ log_level }}"
        force:     "{{ force }}"
        action: ibmsecurity.isam.web.reverse_proxy.configuration.entry.set
        isamapi:
          reverseproxy_id: "{{ file.split('/').1 }}"
          stanza_id:       "{{ item.key }}"
          entries:         "{{ item.value }}"
      loop: "{{ config|seim_reverse_proxy_config_filter|dict2items }}"
```
The  key and value are set, as seen below:

```
...
            "isamapi": {
                "reverseproxy_id": "xxxxxx",
                "stanza_id": "mmfa-config-info",
                "entries": [
                    [
                        "autoconfig",
                        "mmfa"
                    ]
                ]
            },
            "action": "ibmsecurity.isam.web.reverse_proxy.configuration.entry.set",
...
```

I don't expect the "entries" value should be a string?

Kind regards,
Toon

**Comment by sygilber** [comment]
On my end, I do see also similar API call in verbose mode:

>             "isamapi": {
>                 "entries": [
>                     [
>                         "autoconfig",
>                         "mmfa"
>                     ]
>                 ],
>                 "reverseproxy_id": "xxxxxxx",
>                 "stanza_id": "mmfa-config-info"
>             },

Given that they are identical, not sure what is not working on your end.

But what I find odd with the shared code snipet of your, is the passing of "item.key" to the "stanza_id" parameter. key/value pairs should be passed in "entries[ [key1,value1], [key2,value2],...]".

Without suggesting that you should not use your own code, can we for a minute have you try this role, which is standard in the isam-ansible-roles repo (like above) ?

> - role: set_reverseproxy_conf
>   set_reverseproxy_conf_entries:
>     - { stanza_id: "mmfa-config-info", entries: "[['autoconfig','mmfa']]" }
> 

At least, if it works, we could then work out from there what to do next in your own code if you want to stick to it to make it work.

**Comment by toonvdn** [comment]
I'm "happy" that it doesn't work with the role and the hardcoded values that you suggested, which means I have to find it on another level.

I'm using Python 2.7.5 btw. Is version 3 already completely supported?

**Comment by toonvdn** [comment]
Found the issue!

On line 124 of web/reverse_proxy/configuration/entry.py, there is this line:
return _add(isamAppliance, reverseproxy_id, stanza_id, set_entries)

A few lines earlier, set_entries is set to an empty array, so it will never work, UNLESS force is set to False - which we don't want in our case.

So, when changing set_entries to entries, it works.

**Comment by toonvdn** [comment]
I noticed all values being set twice, so they're being added, instead of set, while I'm using the:
action: ibmsecurity.isam.web.reverse_proxy.configuration.entry.set

I guess this is not expected behaviour.
