### ISSUE TITLE
Idempotency broken (server_connections/ws.py)

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/ibmsecurity#194]
Latest updates broken idempotency for server_connections/ci.py.

I believe if 'password' is not provided in a connection (or not required), then code should not force update because 'password' cannot be retrieved from Appliance.

Also, some useful log debugging statement were also removed.

Will try to work out a new revision that still supports idempotency, and not reject it unitarily, and re-introduce debug logging statement.

**Comment by ram-ibm** [comment]
Hoping to get some data on this please. Perhaps a JSON showing the input with the password field?

Alternately - a pull request? :-)

**Comment by sygilber** [comment]
@ram-ibm PR https://github.com/IBM-Security/ibmsecurity/pull/195 for this has been submitted some time ago.

**Comment by sygilber** [comment]
Resolved by https://github.com/IBM-Security/ibmsecurity/pull/195/files
