### ISSUE TITLE
Attach Resource inside API Protection is missing a type supported by the LMI

### ISSUE THREAD

**Issue by Scoi4101** [IBM-Security/ibmsecurity#199]
IBM Security Access Manager 9.0.4

curl -k -v -H "Content-Type: application/json" -u 'blah':blahblah' -X PUT https://$hostname/iam/access/v8/policyattachments/10/policies?action=add \
-d '[{"id":"6","type":"definition"},{"id":"7","type":"definition"}]'

This rest API will work and the LMI supports it as well but the framework only support policy and policysets at this time.

Can we support the API protection / definition policy types ?

Thanks

**Comment by ram-ibm** [comment]
ibmsecurity.isam.aac.acccess_control.policy_attachments.py -- I believe this is already supported? - unless you are looking for something else?

**Comment by Scoi4101** [comment]
Sorry - adding more detail as its supported but a function inside of the conversion code doesn't support the policy type 

using this role
  roles:
    - role: aac/configure_access_control_policy_attachments
      access_control_policy_attachments:
        - server: "{{ da_name }}"
          resourceUri: "{{ da_resource }}"
          attachments:
            - name: "salesforce_broker_oidc_def"
              id: 6
              type: "definition"
            - name: "reporting_app_broker_oidc_def"
              id: 7
              type: "definition"
          action: "set"
      ignore_errors: true

That python module is called by then inside of the coverting the id to the name section it throws a IBM 999 error

https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/aac/access_control/policy_attachments.py#L278

I believe another if condition is needed for the policy type of definition and then a lookup against the definitions list to find the name for the given id

**Comment by djorgen-ibm** [comment]
The check for "definition" is in the current version.
