### ISSUE TITLE
I believe logical flow defect with the set method for oauth clients when the force flag is set to true

### ISSUE THREAD

**Issue by Scoi4101** [IBM-Security/ibmsecurity#204]
I believe logical flow defect with the set method for oauth clients when the force flag is set to true

I call the set operation
https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/aac/api_protection/clients.py#L328

In my use case the client exists so it flows to the update process
https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/aac/api_protection/clients.py#L189 

In my case I am setting the force to be true as an ever
So this line is evaluated as true
https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/aac/api_protection/clients.py#L225

I believe the issue too be than when force is true non of the supplied data is overlaid from the json response of the get

It simply calls the update api with the existing json data

https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/aac/api_protection/clients.py#L317

Thanks for your time

**Comment by ram-ibm** [comment]
Most of our use cases rarely leverages the force flag - so this did not get caught. Yup the JSON data build needs to be outside of the "if force is not True" block.

**Comment by pdavis74** [comment]
How about posting training on this shit

Patrick Davis

**Comment by ram-ibm** [comment]
Ansible out-of-box does not work with ISAM appliances - the framework created here is to provide a seamless integration so Ansible can talk to ISAM like it does with other devices. I speculate Ansible training would be the most useful. Though it would help to understand where the trouble is?

**Comment by djorgen-ibm** [comment]
The has been fixed and merged.
