### ISSUE TITLE
Apply Snapshots only work if force=true

### ISSUE THREAD

**Issue by elijah-chan** [IBM-Security/ibmsecurity#205]
Hi we are trying to apply snapshots with comments instead of the snapshot id, it seems like the logic for the base/apply_snapshots only apply the snapshot if force is set as "true" ?

**Comment by ram-ibm** [comment]
apply_flag is not getting set to True when comment is provided. Yup that is a bug.

**Comment by djorgen-ibm** [comment]
The has been fixed and merged.
