### ISSUE TITLE
Applying minHeapSize/maxHeapSize first time

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/ibmsecurity#206]
Getting a strange behavior but I will take some more time to analyse in the coming days:

a) Administrator's min/maxHeapSize not set yet on Appliance (showing as "Unset" in the LMI):

b) On curl's side min/maxHeapSize don't show neither

```
curl -k --user admin@local:password -H "Content-Type:application/json" -H "Accept: application/json" -X GET https://someappliance/admin_cfg
{"consoleLogLevel":"OFF","enabledTLS":["TLSv1","TLSv1.1","TLSv1.2"],"minThreads":-1,"maxFileSize":20,"acceptClientCerts":true,"httpsPort":443,"sessionCachePurge":120,"sshdPort":22,"enabledServerProtocols":"TLSv1.2","validateClientCertIdentity":false,"lmiDebuggingEnabled":false,"sessionInactivityTimeout":30,"sessionTimeout":120,"sshdClientAliveInterval":300,"enableSSLv3":false,"maxThreads":-1,"maxPoolSize":100,"maxFiles":20}
```

c) Using RESTAPI to set for the first time values ends OK with just a pending Commit to complete, which in turns has the LMI automatically restart and it is coming back online OK

```
curl -k --user admin@local:password -H "Content-Type:application/json" -H "Accept: application/json" -X PUT https://someappliance/admin_cfg -d "{"consoleLogLevel":"OFF","enabledTLS":["TLSv1","TLSv1.1","TLSv1.2"],"minThreads":-1,"maxFileSize":20,"acceptClientCerts":true,"httpsPort":443,"sessionCachePurge":120,"sshdPort":22,"enabledServerProtocols":"TLSv1.2","validateClientCertIdentity":false,"lmiDebuggingEnabled":false,"sessionInactivityTimeout":30,"minHeapSize":1024,"maxHeapSize":2048,"sessionTimeout":120,"sshdClientAliveInterval":300,"enableSSLv3":false,"maxThreads":-1,"maxPoolSize":100,"maxFiles":20, "minHeapSize":1024,"maxHeapSize":2048}"
{"consoleLogLevel":"OFF","enabledTLS":["TLSv1","TLSv1.1","TLSv1.2"],"minThreads":-1,"maxFileSize":20,"acceptClientCerts":true,"httpsPort":443,"sessionCachePurge":120,"sshdPort":22,"enabledServerProtocols":"TLSv1.2","validateClientCertIdentity":false,"lmiDebuggingEnabled":false,"sessionInactivityTimeout":30,"minHeapSize":1024,"maxHeapSize":2048,"sessionTimeout":120,"sshdClientAliveInterval":300,"enableSSLv3":false,"maxThreads":-1,"maxPoolSize":100,"maxFiles":20}
```

d) However, using the Ansible/Python stack to try setting those values for the first time results in the LMI automatically restarting as expected but it never comes back online. To recover from such situation, I am using CMI's "lmi revert_config" command.

Next step I will enable Ansible debug mode and maybe some traces in the LMI, using again CMI's "lmi revert_config" command to bring back LMI's settings in its original factory defaults.

**Comment by ram-ibm** [comment]
I am wondering if we need to run the python code with -vvv and see how the JSON is formed and match it with what you have in step (c).

**Comment by sygilber** [comment]
Not able to reproduce the issue for now thus closing the item. May have been some "programmer" error.
