### ISSUE TITLE
Best Practices

### ISSUE THREAD

**Issue by daniew01** [IBM-Security/ibmsecurity#207]
Hi

Some back ground :
I am currently do all development in a separate server then once I am happy I move the yaml files to the production server. I refreshed the repository last year from GitHub and then things failed on the development server as the roles.

I was wondering, taken future upgrades into consideration, what is the better option to use for preparing a production environment. Do I create a python virtual env for example: 
  - python -m venv /opt/ansible001
Or do I just prepare the servers with all the required packages and do a pip upgrade as needed?

Kind Regards
DJW

**Comment by ram-ibm** [comment]
What kind of errors did you face please?

My strategy has been to always have playbooks that are environment independent - and then use the inventory to capture all environment specific values. For example, pre-prod uses a different syslog_receiver from PROD. So the inventory has a variable that populates the right value for each environment. Then the playbook simply uses that variable when a syslog_receiver ip or hostname is needed.

The code should be backwards compatible - we are working through some issues with the code being python3 compatible though.

The python best practice is to use venv - but hoping to understand your issues faced to figure out what could avoid it in the future.

**Comment by daniew01** [comment]
Thnx Ram

I have been sorted
