### ISSUE TITLE
Python 3.8 encoding problem in function files_same

### ISSUE THREAD

**Issue by riccardomassullo** [IBM-Security/ibmsecurity#208]
Using python 3.8 (on Archlinux) and trying to upload an already existent dynurl file the following error is thrown:
`Traceback (most recent call last):
  File "test_ibmsecurity.py", line 86, in <module>
    p(ibmsecurity.isam.web.url_mapping.import_file(isamAppliance=isam_server, force=False, id="dynurl.conf", filename="files/dynurl.conf"))
  File "/usr/lib/python3.8/site-packages/ibmsecurity/isam/web/url_mapping.py", line 148, in import_file
    if force is True or _check_import(isamAppliance, id, filename, check_mode=check_mode):
  File "/usr/lib/python3.8/site-packages/ibmsecurity/isam/web/url_mapping.py", line 189, in _check_import
    if files_same(tmp_original_file, filename):
  File "/usr/lib/python3.8/site-packages/ibmsecurity/utilities/tools.py", line 174, in files_same
    hash_original_file = hashlib.sha224(original_file_contents).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
`
The cause is in the following lines:
https://github.com/IBM-Security/ibmsecurity/blob/3d5d781602710a0e0d31c948a3c4bd038b7ff7cb/ibmsecurity/utilities/tools.py#L174
https://github.com/IBM-Security/ibmsecurity/blob/3d5d781602710a0e0d31c948a3c4bd038b7ff7cb/ibmsecurity/utilities/tools.py#L175

Modifying the line 174 to:
`hash_original_file = hashlib.sha224(original_file_contents.encode()).hexdigest()`
and line 175 to:
hash_new_file = hashlib.sha224(new_file_contents.encode()).hexdigest()

solves the problem.

**Comment by ram-ibm** [comment]
Thanks we will fix this.

**Comment by ram-ibm** [comment]
This should now be fixed.
