### ISSUE TITLE
Idempotency for Username mapping is wrong when running in check mode

### ISSUE THREAD

**Issue by Warkdev** [IBM-Security/ibmsecurity#217]
Hello folks,

I've noted that this method was properly idempotent in executed mode but when running check mode, it returns always "Changed = True": https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/web/user_name_mapping.py#L79

I think it's a matter of copy/pasting to make both version idempotent :)

And by the way, why not checking idempotency by default before checking the run mode ?

Cédric Servais

**Comment by ram-ibm** [comment]
Agreed - will look into this.

**Comment by djorgen-ibm** [comment]
Fix has been merged.
