### ISSUE TITLE
ibmsecurity.isam.statistics.get_rp_throughput_summary doesn't return actual throughput data

### ISSUE THREAD

**Issue by ibm-enio** [IBM-Security/ibmsecurity#222]
When running ibmsecurity.isam.statistics.get_rp_throughput_summary(isam_server, "1586806180", "86400", "junction") I get back the data shown below, which doesn't include the actual throughput data as shown in the documentation:

{'status_code': 0, 'changed': False, 'data': {u'time_span': 86400, u'tzname': u'GMT', u'tz_offset': -14400000, u'last_bucket': 1586892580, u'first_bucket': 1586806180}, 'rc': 0, 'warnings': []}

By looking in the LMI, it looks like it is actually making 2 calls to get the throughput data back, but the python script is only making one call, so we never get the actual throughput data.

**Comment by ram-ibm** [comment]
Typical calls in the framework make just one call. The Ansible portion of it combines to make multiple calls if needed. Do you know which are the two REST API calls in LMI please?

**Comment by ibm-enio** [comment]
These are the two calls and response I can see in the LMI:

Request URL: https://isam.mmfa.ibm.com/analysis/reverse_proxy_traffic/throughput/?summary=true&date=1586790000&duration=3600&aspect=junction
Request Method: GET
Response: {"first_bucket":1586790000,"time_span":3600,"tz_offset":-14400000,"last_bucket":1586793600,"tzname":"GMT"}

Request URL: https://isam.mmfa.ibm.com/analysis/reverse_proxy_traffic/throughput/?date=1586790000&duration=3600&aspect=junction
Request Method: GET
Response: [{"a":"api-gateway","b":600,"t":1586790000,"h":14}, {"a":"dashboard","b":600,"t":0,"h":0}, {"a":"default","b":600,"t":1586792400,"h":29}]

I tried to do the second call right after the first, but I get an HTTP 500 when I make the second call without the summary=true parameter.

**Comment by ibm-enio** [comment]
See the doc below, which points there is an additional header required to get the appropriate output for the traffic RAPI.  Should this be implemented in the script?

https://www.ibm.com/support/pages/node/4822233

**Comment by ram-ibm** [comment]
Thanks for the documentation - yup we need to add the additional header. Will add it to our bug list.
