### ISSUE TITLE
Template files not implemented

### ISSUE THREAD

**Issue by ghost** [IBM-Security/ibmsecurity#23]
Hi Ram,

I'd like to use -
https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/aac/runtime_template/files.py

Do you want me to put together an implementation in your style as a pull request?

Cheers,
David

**Comment by ram-ibm** [comment]
David - that would be wonderful. I was planning to clone this:
https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/web/reverse_proxy/management_root/file.py

I believe most of the logic is similar.

**Comment by dal-ibm** [comment]
Wound up using the zip upload feature in file.py, which may not work either. Currently under discussion (with a proposed fix) in #24.
