### ISSUE TITLE
Idempotency of the module

### ISSUE THREAD

**Issue by Warkdev** [IBM-Security/ibmsecurity#234]
Hello, first of all, that's fantastic to have this module available to get started with Ansible. 

However, I'm having quite some headaches so make good use of it while organizing our inventories. We're in an environment into which we'd like to enforce configuration standards and lower the required configuration input and, on the same time, using a highly consolidated infrastructure which means that we're several to work inside the same repositories.

What is definitly inside Ansible guidelines is that playbook must be idempotent, today with the current module setup, we're forced to workaround the module to virtually add this idempotency (using custom filters or extra admin-calls). It would be great if this module could be, out-of-the-box idempotent or documented whether a function is idempotent or not.

I've crossed files with "set" "update" "add" methods. I've crossed modules which reports "Updated" in check mode in any case, pdadmin calls are never idempotent. I haven't come accross yet any file which would delete objects which are present on the appliance but not in the inventory anymore.

Do you guys have plans to improve idempotency ? Do you have expectations ?

Thanks,

Cédric S.

**Comment by Warkdev** [comment]
Adding on my own comment.

If you want also to have help on improving this module, it could be nice to have some ISAM lab available that we can test against it :)

Cédric S.

**Comment by ram-ibm** [comment]
The primary objective of the ibmsecurity python code is to provide idempotency. Having said that PDAdmin had logic to provide idempotency - but it would not scale. So that code was put on hold. Please indicate which function is not idempotent - fyi force variable is provided to override idempotency. If you are setting that to True then you are effectively turning off idempotency logic.

**Comment by Warkdev** [comment]
Hello Ram,

Thanks for the feedback. What were the scalability issues of the pdadmin idempotency ? We do leverage it using custom filters inside custom roles which seems to work ok.

Regarding the idempotency, I've a general remark:
- When launched in check mode, most of the functions won't check for idempotency, they will just return changed=true in this case, which is wrongly indicating to the deployer that something is different. For instance, the signer_certificates.py is checking if a file is different between importing it (providing effective idempotency) while personal_certificates.py is only checking that the file exist (https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/base/ssl_certificates/personal_certificate.py#L147).

To me, idempotency goes further than just verifying if a file exists. There's also a need to verify its attributes. For instance, junction mapping will only verify that the file exists but it won't check if the content has changed: https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/web/junction_mapping.py

Some functions are providing 'set' methods which add or update but that's not really idempotent, it's rather "making sure that the generated version is the one being deployed".

At the end of the day, what we want is that when you run your playbook and that nothing had a need to change, there's no task reported as "changed", right ?

Cédric S.

**Comment by ram-ibm** [comment]
See Issue#10 where we tracked PDAdmin idempotency. The code is not very sophisticated - but works for small number of commands. I'll see if I can dig it up and post it - it will be to issue#10.

The effort to ensure idempotency runs into issues like needing passwords that does not have a easy resolution. For those kind of situations it is the best we can do.

Having said that junction_mapping could use better idempotency check when we import a file. The logic to download and execute a hash compare came later - and was not added to all modules.

Happy to take a pull request if you have an immediate need to fix some of the idempotency deficiencies.

**Comment by Warkdev** [comment]
Hey ram,

I've submitted some PR that may be interesting for this. I've sadly no way to test them as I don't have a DEV environment available where I can dev this.

However, this should work properly as the logic is redundant and already used elsewhere.

The work you did for idempotency of pdadmin is pretty strong but I should admit that it's a huge thing. We've preferred to use custom filters and roles to handle that aspect and it works pretty well.

Cédric S.
