### ISSUE TITLE
Cannot search/update authentication policies by URI

### ISSUE THREAD

**Issue by ghost** [IBM-Security/ibmsecurity#25]
At present the only way to search/update policies is by name. It's not possible to search by URI, or enabled, etc. It's also not possible to search for multiple policies at once, as name is unique. I think these are pretty important features.

I can modify search/update to use the existing filter system in the RAPI, but it'll be an interface change for existing code using this library.

What do you think?

Update: https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/aac/authentication/policies.py#L102
Search: https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/aac/authentication/policies.py#L167

**Comment by dal-ibm** [comment]
Pull request opened in #28.

**Comment by ram-ibm** [comment]
The get_all() function has been typically used to provide the query parameters for limiting the search. See the following as an example:

```
def get_all(isamAppliance, filter=None, sortBy=None, check_mode=False, force=False):
    """
    Retrieve a list of policies
    """
    return isamAppliance.invoke_get("Retrieve a list of policies",
                                    "{0}/{1}".format(uri, tools.create_query_string(filter=filter, sortBy=sortBy)))
```

The search() function is basically to get the UUID for a given object and is thus limited to searching for just one name. I just looked at the REST API documentation and realize that the search parameters have not been coded for the get_all() function. This maybe a cleaner solution and will keep the rest of the code in sync.

**Comment by dal-ibm** [comment]
As get_all() can search already, that's great and obsoletes that component.

What about update()? I think making those parameters optional is a nicer API for developers than copying in the data found from the get.

**Comment by ram-ibm** [comment]
I made the necessary code changes to get_all(). I ran a few simple tests like so:
```
ibmsecurity.isam.aac.authentication.policies.get_all(isamAppliance=isam_server, count=2, filter='description%20contains%20Consent')
```
Seems to be working. Code changes submitted. Please try it out.

**Comment by ram-ibm** [comment]
Let me have a look at update() I missed that.

**Comment by ram-ibm** [comment]
I looked at the code in your pull request and am not clear what you are looking to do. I would like to avoid providing "id" and do a lookup using the name. That makes it more friendly - though it entails an extra lookup.

I did not realize we can pass lastmodified, datecreated, userlastmodified when we do an update. Wonder if we need to make sure add() needs those parameters as well? Maybe add predefined as well?

**Comment by dal-ibm** [comment]
Under the current implementation of update, is there a way to rename a policy?

"id" is useful because it's the only immutable attribute of a policy, so we can say "update the policy with id 29 and set its name".

I don't know about those dates. It seems odd to be manipulating them directly, but the RAPI seems to allow it. No opinion.

Also of note is that using optional named parameters in update means calls can be much shorter and harder for a developer to get wrong.

**Comment by ram-ibm** [comment]
Closing this for now since the framework seems to be working well for Policies - have been using it extensively.
