### ISSUE TITLE
API Protection Definition - int to string Ansible/Jinja bug

### ISSUE THREAD

**Issue by Franclaf7** [IBM-Security/ibmsecurity#252]
Hello,

We were trying to set an API protection definition using Ansible playbooks/inventories. While hardcoding the int value in the playbook for the parameters needing an int worked out fine (accessTokenLifetime, maxAuthorizationGrantLifetime, etc), it suddenly stopped working when we switched to using the inventories. Even with the Jinja "int" filter, the value passed was being cast as a string, with no way of passing it back as an int from Ansible.

Error message:
"('HTTP Return code: 400', u'{\"result\":\"FBTRBA241E The JSON property [lifetime] received an invalid type of [type]. The expected type was [[number]].<br>FBTRBA241E The JSON property [refreshTokenLength] received an invalid type of [type]. The expected type was [[number]].<br>FBTRBA241E The JSON property [maxAuthorizationGrantLifetime] received an invalid type of [type]. The expected type was [[number]].<br>FBTRBA241E The JSON property [accessTokenLifetime] received an invalid type of [type]. The expected type was [[number]].\"}')"

A small fix in the Python code worked for us: in the isam/aac/api_protection/definitions.set() function, we simply force casted each parameters to an int before either the add() or the update() function were called. 

We will wait for your reply before opening a PR.

Thank you

**Comment by ram-ibm** [comment]
I saw one other code submission that had cast the value to be an int inside the python code. The framework was build assuming user understood what data to pass - since this cannot be controlled because of a jinja bug, go ahead and open a PR. We will not be looking to casting to right values for ALL calls.
