### ISSUE TITLE
Setting up entry with "?" doesn't work

### ISSUE THREAD

**Issue by Warkdev** [IBM-Security/ibmsecurity#253]
Hello,

In the reverse-proxy configuration file (webseal.conf), there could be stanza with entries starting by or containing question mark character "?".

For instance, the stanza "filter-url" contains by default the entry "?IMPORT" with a value "IMPLEMENTATION".

I've tried many combinations of YAML definition (even naming ?IMPORT -> %3FIMPORT) but the framework always consider that there's a change and is either pushing %3FIMPORT or a new row for ?IMPORT.

I think that the entry name must be encoded and decoded as the entry value seems to be.

Regards,

Cédric S.

**Comment by ram-ibm** [comment]
Interesting issues... not had to deal with this. Will try to re-create and see how to fix it.

**Comment by Warkdev** [comment]
I've locally fixed this by applying a similar principle as you already have for the "delete" function: https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/web/reverse_proxy/configuration/entry.py#L180

Applying this logic on the entry value of the update and get functions makes it to work properly (https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/web/reverse_proxy/configuration/entry.py#L227)
