### ISSUE TITLE
Doesn't support docker deployment

### ISSUE THREAD

**Issue by jameson71** [IBM-Security/ibmsecurity#256]
'warnings': [ 'API invoked requires model: Appliance, appliance is of '
                'deployment model: Docker.',
                'API invoked requires model: Appliance, appliance is of '
                'deployment model: Docker.']}

**Comment by ram-ibm** [comment]
You are calling a REST API that is specific to Appliance. We now have logic that throws the warning you see -- some REST APIs are specific to only Docker or Appliance, though there is a bunch that is compatible with both.
