### ISSUE TITLE
ibmsecurity.isam.web.client_certificate_mapping.import_file is not idempotent

### ISSUE THREAD

**Issue by Ardun21** [IBM-Security/ibmsecurity#26]
I noticed that when using the ibmsecurity.isam.web.client_certificate_mapping module to import a certificate mapping rule that already exists, playbook execution is halted because of an error from the appliance stating:

A Client Cert Authentication Module File already exists with that name. {{ mapping file name }}

Ideally this module should first check to see if a cert mapping rule already exists with the given name and skip the import call if it does.

**Comment by ram-ibm** [comment]
I think we looked at this and had to skip the idempotency logic. Let me look to see if I can get more information.

**Comment by ram-ibm** [comment]
The code has logic to delete and replace the rule if there is a difference. Could you provide a trace of your execution please?

**Comment by ram-ibm** [comment]
Closing for now, please re-open when you have more information. Thanks.
