### ISSUE TITLE
Web Runtime Configuration _collapse_entries is wrong

### ISSUE THREAD

**Issue by Warkdev** [IBM-Security/ibmsecurity#285]
Hello,

Just wanted to let you know that this code [snippet](https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/web/runtime/configuration/entry.py#L136) generating duplicate keys:

You should instead use the following code (as in t he WRP configuration entry.py):

`
else:
            new_entry.append([cur_key, cur_value])
            # reset current key
            cur_key = entry[0]
            cur_value = [entry[1]]
`

Regards,

Cédric Servais

**Comment by djorgen-ibm** [comment]
Hello,

Which file did you identified the issue in?  Clicked on the link to the code snippet and it pointed to web runtime configuration entry's _collapse_entries and has the same code as in your comment.

I tested the _collapse_entries with: 
entries=[['key', 'value1'], ['key', 'value2'], ['key1', 'value1'], ['key1', 'value2']]

and the result was as expected:
[['key', ['value1', 'value2']], ['key1', ['value1', 'value2']]]

Thanks,
Diana

**Comment by Warkdev** [comment]
Hello Diana,

You're right, we've duplicated your codebase some months ago and I had to fix it lately, meanwhile, you have fixed it too in this [commit](https://github.com/IBM-Security/ibmsecurity/commit/206450095712da81f182402e5d90302012734b7d)

Apologize,

Cédric Servais
