### ISSUE TITLE
Setting advanced tuning parameters via REST API doesn't work if more than one parameter has the same key

### ISSUE THREAD

**Issue by Ardun21** [IBM-Security/ibmsecurity#29]
We typically set a number of advanced tuning parameters on ISAM as recommended via the PMR process. Two of these parameters have the same key: runtime_profile.jvm_option

I have noticed that if I try to set both parameters via the REST API, only the second one actually ends up being set. I assume that because both parameters have the same key, the call to add the second one ends up overwriting the first one.

Strangely, we do not have this problem if we set the parameters via the LMI. Given that the LMI by and large just makes calls to the REST API to achieve its functionality, I'm not really sure what the difference is here that allows the LMI to do this when just calling the REST API cannot.

**Comment by ram-ibm** [comment]
The actual tuning parameters have UUID assigned to them on the appliance. The Python code assumes the key is unique to implement idempotency. I will need to look at the code again to see if we can handle your particular use case.

**Comment by sygilber** [comment]
Could the above description explains also why when using the role set_runtime_tuning_parameter that idempotency does not seem to work ?

```
TASK [set_runtime_tuning_parameter : Set Runtime Tuning Parameters] ****************************************************************************************************
changed: [someserver] => (item={u'runtime_tuning_parameter_value': u'false', u'runtime_tuning_parameter_option': u'enable_sslv3'})
changed: [someserver] => (item={u'runtime_tuning_parameter_value': u'rt_keys', u'runtime_tuning_parameter_option': u'keystore'})
changed: [someserver] => (item={u'runtime_tuning_parameter_value': u'somelabel', u'runtime_tuning_parameter_option': u'keystore_label'})
changed: [someserver] => (item={u'runtime_tuning_parameter_value': u'sometruststore', u'runtime_tuning_parameter_option': u'truststore'})

```

**Comment by ram-ibm** [comment]
You can simply set force = True to skip idempotency to add multiple values as a workaround.

**Comment by ram-ibm** [comment]
I am not able to think of a good way to handle this. If we consider key+value as unique then when you set a value like so:
key - "timeout-value"
value - "60"

Then if you want to change the timeout to 90 you would need to delete the 60 value and add it back as 90. simply updating 60 to 90 will not work. It is possible that this is how it should have worked all along.

**Comment by ram-ibm** [comment]
I changed the python code for this - you will be able to provide an array for values for the same key. Something like this:
```
key: "multiple-values"
value:
  - 10
  - 20
```

The next ibmsecurity package update will contain this fix. Closing this out.
