### ISSUE TITLE
disabling management for ISAM update servers

### ISSUE THREAD

**Issue by lilmano18** [IBM-Security/ibmsecurity#33]
"Update Servers" found under LMI has no API counter parts in ibmsecurity module

**Comment by wdwill2wdwill2** [comment]
Not sure what you want to do with "Update Server", but i didn't want the appliance to phone home for any  updates.

I added this value to the advanced tuning parameters.

update.disable.remote.discovery  with a value of 1.

It seemed to work for me, and advanced tuning parameters is a role.

Thanks

**Comment by lilmano18** [comment]
thks a lot . i dont see the update servers 's enable check box be disabled but in advanced tuning parameters i added a paramters : 
       - key : update.disable.remote.discovery
       - value : 1
       - comment : xxxxxxxxx

**Comment by ram-ibm** [comment]
I am working on code for this - will submit when it is tested and ready. The following are in the works:
update_servers.py
application_database_settings.py
scheduled_security_updates.py

As noted please be sure to set the advanced tuning parameter as well as documented here:
http://www-01.ibm.com/support/docview.wss?uid=swg21698790

**Comment by lilmano18** [comment]
YEAH , thts what i made since the last time. i can submit you what i made or you prefer work yourself . because i work with my supervisor on you ibmsecurity library and ibmsecurity roles and we already have implemented some roles , so if u are interested we can submit them to you and u will test and push them.

**Comment by ram-ibm** [comment]
Sorry about the delay - trying to find time to complete the modules.

**Comment by lilmano18** [comment]
no problem :)

**Comment by ram-ibm** [comment]
Three modules have been added to the python code base. They are:
update_servers.py
application_database_settings.py
scheduled_security_updates.py

They need Ansible Roles.
