### ISSUE TITLE
Idempotency not available when call action ibmsecurity.isam.base.management_ssl_certificate.set

### ISSUE THREAD

**Issue by bjsong19** [IBM-Security/ibmsecurity#341]
We created a Ansible Role like below. It is executed and uploaded the LMI certificate. but we got warning message:
[WARNING]: Idempotency not available. Unable to extract existing certificate to compare with provided one.

Another issue is after this SSL certificate updated, the appliance did not apply this certificate until a manual appliance restart. looks the Commit Changes did not restart the appliance.

#Role to reset LMI Management SSL Certificate:
- name: "Set LMI management SSL certificate [-e lmi_ssl_cert=<lmi ssl p12 file location> -e lmi_ssl_password=<certificate password>]"
  ibm.isam.isam:
    log: "{{ log_level | default(omit) }}"
    force: "{{ force | default(omit) }}"
    action: ibmsecurity.isam.base.management_ssl_certificate.set
    isamapi:
      certificate: "{{ lmi_ssl_cert }}"
      password: "{{ lmi_ssl_password }}"
  when:
    - lmi_ssl_cert is defined
  notify: Commit Changes

**Comment by ram-ibm** [comment]
Idempotency works by querying the existing value and comparing it with that being passed to ansible to update. Since there is no API to extract the certificate in this situation - we are unable to check if a change is required. Ansible will hence make the update every time.

You should be able to see if the Commit Changes handler ran after the update?

**Comment by Cedric-Ser** [comment]
Hello @ram-ibm, the API does allow you to query the keystore properties and therefore build a diff around it.

It requires a bit of work but isn't that difficult :)

**Comment by ram-ibm** [comment]
I recollect that the data was not available for doing a diff - maybe there is a new API for it since then? It will need someone with more time than me to investigate and fix (if at all possible).

**Comment by Cedric-Ser** [comment]
There's an API (I think it already existed) to provide this:

{"keysize":"2048","notbefore":"March 15, 2013 12:00:00 AM GMT+01:00","subject":"\"CN=...\"","notafter":"June 13, 2053 11:59:59 PM GMT+02:00","version":"X509 V3","issuer":"\"CN=...\""}

You can generate the very same JSON out of the key you wish to import and compare them.

It's not 100% perfect of course but it's a pretty solid hint. The other option is to download the pub key from the SSL connection and compare it with the data you've locally.
