### ISSUE TITLE
available_updates.py is not up to date

### ISSUE THREAD

**Issue by nbarni94** [IBM-Security/ibmsecurity#385]
We found an error in the available_updates.py during our update process.

An exception occurred in line 138 with the following error

```
if upd['state'] == 'Installing':
   KeyError: 'state'
```

As we can see the ['state'] parameter is not exists anymore on the https://{appliance_hostname}/updates/available API from the 10.0.5 version. The IBM documentation is also not up to date.

Could you please fix the code?

**Comment by tombosmansibm** [comment]
Hi , I will pick this up.

**Comment by tombosmansibm** [comment]
Note that there's also a change in the expected value for "name" 
 the "name": "Firmware" in 10.0.3.0-->10.0.4.0 must now be "name": "isva" in 10.0.4.0 -> 10.0.5.0

**Comment by tombosmansibm** [comment]
`updates:
  - file: '/home/tbosmans/Downloads/IBM/ISAM/10.0/10.0.6/isva_10.0.6.0_20230529-0304.pkg'
    version: 10.0.6.0
    date: '2023-05-29-0304'
    name: isva
    type: firmware
`
Make sure the collection is there:
`ansible-galaxy collection install -r collections/requirements.yml -p ./collections`

Development mode install in the virtual env.
`pip install -e ~/ibmsecurity/`

Upload the pkg
`ansible-playbook -i inventories/local/ -l v1006 ibm.isam.base.upload_updates -vvv -e 'homedir=""'`

Install the update
`ansible-playbook -i inventories/local/ -l v1005 ibm.isam.base.install_update -v -e 'name=isva' -e 'type=firmware' -e 'version=10.0.6.0' -e 'release_date=2023-05-29-0304'`
