### ISSUE TITLE
management ssl certificates

### ISSUE THREAD

**Issue by lilmano18** [IBM-Security/ibmsecurity#39]
I observed a behavior in the python code from the file ibmsecurity/isam/base/management_ssl_certificate. In this file , when i looked at the function set i noticed that the invocation of method  ' check (isamAppliance) ' instead of ' check (isamAppliance, certificate, password) '.
When i tried to update management ssl certificates of my isam appliance by creating a new role i got this error :  "Error> action does not have the right set of arguments or there is a code bug!
Firstly what i made is to correct the function ' check ' call by adding the missing parameters.
There after i get further but now , i got this error : "The request could not be completed as it would leave the configuration in an invalid state. : /var/www/lmi/tmp/path_to_my_cert_on_centOS (No such file or directory)\".
So what i made is reading  lmi tracing to debug by updating  management ssl certificate using the lmi and after using playbook. But when i used playbook in the lmi tracing i saw warning error "ignoring parameter"

**Comment by ram-ibm** [comment]
_check() function has not been coded since there is no way to examine existing certificate on the appliance with what you have provided - i.e. there is no idempotency. But you are right the function call needs to provide the right parameters. I made the fix.

What version of the appliance are you on? May need to check with the folks who wrote the code what they tested on...

**Comment by lilmano18** [comment]
we are using isam 9.03

**Comment by lilmano18** [comment]
**** new alert *** 
my teammate and me trying to isolate the problem so we used testisam.py to test the python code.
we remarked that instead of passing the long path of the license file if we put the certificate file in testisam.py file directory and pass the short path, we got no problem . It means that instead of path_to_my_cert_on_centOS we putted name_of_cert and it worked. Why should i necessarely put the cert file in the same directory of my testisam.py ? what to do if my cert file is in another directory ?

**Comment by ram-ibm** [comment]
All files that we import are fully qualified. So that does not sound right. I do not have a SSL certificate to test with at the moment. Would it be possible to provide a trace with the error please?

**Comment by sygilber** [comment]
Ram

You will find attached 2 files which show the working scenario (invoking python code referring to a p12 key store located in the same directory as the python code) and the not working scenario (invoking python code referring to a p12 key store located in a different directory and using a fully qualified path).

[testisam_managementsslcertificate.py_fullpath_filename_FAILURE.txt](https://github.com/IBM-Security/ibmsecurity/files/1251815/testisam_managementsslcertificate.py_fullpath_filename_FAILURE.txt)
[testisam_managementsslcertificate.py_short_filename_OK.txt](https://github.com/IBM-Security/ibmsecurity/files/1251814/testisam_managementsslcertificate.py_short_filename_OK.txt)

One additionnal observation that we made is that management_ssl_certificate.py uses isamAppliance.invoke_post_files() to build and upload the keystore whereas a similar functionality found in license.py (which does accept fully qualified path) is using the isamAppliance.invoke_request() to build and upload the license file.  The RESTAPI syntax for both functions a little bit different it may explain why it does not use the same python code. This is just to say that this could be direction to look into.

**Comment by lilmano18** [comment]
https://github.com/IBM-Security/ibmsecurity/commit/2bf8ba5c374bb43dbb27d8de47d819ba11e3cbf7
