### ISSUE TITLE
isds-ansible-roles

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/ibmsecurity#41]
Hi,

We envision to start working on ISDS Suite V8 automation soon and we would like to do so with Ansible as opposed to just plain python scripts.  We see that the foundation for ISDS Suite automation in the "ibmsecurity" is already laid out.  

What would be the next step ? 

Would it be for IBM to create a new git repository (isds-ansible-roles) and we could start migrating basic administration roles at first (considering what was already achieved for ISAM) ? 

Or would it be for anyone from the community to initialize a private or public git repository and share it once it is mature enough ? It does not need to 100 % complete. Incremental integration I think is more productive (from the bottom to the top features).

Maybe IBM is already working on an ISDS project internally but just not ready to share to it or keeps it for an upcoming announcement ?

In any case, I believe the foundation in the ibmsecurity repository is present, that we need to do a clean select of those isam appliance roles that do share a common denominator with the ISDS appliance (NTP, SYSTEM ALERTS, NETWORKING, etc) even when often different rest api signatures are presented.  This is not a real concerns as the new ISDS roles would make the integration point more uniform.

Comments welcomed.

**Comment by ram-ibm** [comment]
The custom modules for ISDS have not been created. I expect that it will be mostly a clone of isam.py. Typically I have been moving functionality forward when I immediately need it. Maybe it makes sense for the person most in need to start the work? I am happy to create an empty framework for the ISDS roles.

**Comment by sygilber** [comment]
Yes Ram
It would be a good idea for the new project (repo) to be created.and then people can contribute to the area they fell they are the most at ease.
This means for myself writing supporting services code. Maybe I would need to understand what are the absolute minimal set of pythons (besides isds.py) to be developped to be able to launch a playbook and get the start_config role working.

Sylvain


      De : Ram Sreerangam <notifications@github.com>
 À : IBM-Security/ibmsecurity <ibmsecurity@noreply.github.com> 
Cc : Sylvain Gilbert <sylvain_gilbert@yahoo.com>; Author <author@noreply.github.com>
 Envoyé le : samedi 30 Septembre 2017 11h10
 Objet : Re: [IBM-Security/ibmsecurity] isds-ansible-roles (#41)
   
The custom modules for ISDS have not been created. I expect that it will be mostly a clone of isam.py. Typically I have been moving functionality forward when I immediately need it. Maybe it makes sense for the person most in need to start the work? I am happy to create an empty framework for the ISDS roles.—

**Comment by sygilber** [comment]
The original vision trcked by this "issue" has been realized and his now implemented (first cut) by PR https://github.com/IBM-Security/isds-ansible-roles/pull/1.

Thanks for your support.
