### ISSUE TITLE
Federated Registries ignore_if_down check

### ISSUE THREAD

**Issue by lecuongau** [IBM-Security/ibmsecurity#410]
The version check in the federated registries are written as:
            if ignore_if_down and tools.version_compare(isamAppliance.facts["version"], "10.0.4") >= 0:

This means this ignore_if_down is false (either intentionally, or by default), then the attribute ignore_if_down is not added to the REST request.
Which results in a HTTP 500 error as that attribute is required.

**Comment by tombosmansibm** [comment]
That attribute is not required , according to the documentation (see https://ibm-security.github.io/apidocs/verifyaccess/10.0.7.0/ISVA-mgmt-rest-api/index.html)

Are you certain the http 500 error is coming from that particular missing parameter?  

But you are correct, the current code does not allow you to explicitely set ignore_if_down to 'false' , so it needs a little rewrite.

**Comment by tombosmansibm** [comment]
I'll change it to :

            if tools.version_compare(isamAppliance.facts["version"], "10.0.4") >= 0:
                json_data['ignore_if_down'] = ignore_if_down

**Comment by lecuongau** [comment]
Thanks.
It might not be intended behaviour - but I have confirmed what happens using Postman (against 10.0.6).
If we include the ignore_if_down attribute, then the API works fine.
If it is omitted, then the API returns HTTP 500 and the federated directory configuration is only half complete (SSL configuration not set, suffix list not fully populated).
