### ISSUE TITLE
Unable to install new Dynatrace extension

### ISSUE THREAD

**Issue by aditiParimanshu** [IBM-Security/ibmsecurity#415]
Due to below code error unable to install the Dynatrace extension:

https://github.com/IBM-Security/ibmsecurity/blob/3ff140924e2e56b54364a2a78249bc392cec66aa/ibmsecurity/isam/base/extensions.py#L63

def _get_config_data(extId, config_data):

   """

   Generate a JSON payload for activate/update

   """

   if config_data is None:

       return json.dumps({extId: extId}) >>> **Should be return json.dumps({'extId': extId})** 

   if isinstance(config_data, basestring):

       return '{extId:}' + extId + ',' + config_data + '}'  >>> **should be return '{extId:' + extId + ',' + config_data + '}'**

   config_data['extId'] = extId

   return json.dumps(config_data)

Added the correct return statement for the  _get_config_data() method in bold 

Take this issue on priority.
@tombosmansibm please take thiss issue on priority , due to this issue correct json is not getting formed for installing the dynatrace extension

**Comment by tombosmansibm** [comment]
closed by #417
