### ISSUE TITLE
Multiple vulnerabilities found in ibmsecurity

### ISSUE THREAD

**Issue by pba-report-isva** [IBM-Security/ibmsecurity#416]
Redacted

**Comment by tombosmansibm** [comment]
Thanks for bringing this to our attention .

**Comment by pba-report-isva** [comment]
Hello,

can you confirm these issues and let me know if you plan to fix them?

Thank you,

Best regards,

**Comment by tombosmansibm** [comment]
Yes, these will be fixed.

**Comment by tombosmansibm** [comment]
closed by #418

**Comment by pba-report-isva** [comment]
Hello,

can you provide the CVEs and publish the corresponding advisories in https://github.com/IBM-Security/ibmsecurity/security?

Thank you

**Comment by pba-report-isva** [comment]
The security bulletin has been published at https://www.ibm.com/support/pages/node/7147932.

**Comment by tombosmansibm** [comment]
Hi Pierre, we're looking into this.
