### ISSUE TITLE
warnings not initialised

### ISSUE THREAD

**Issue by lecuongau** [IBM-Security/ibmsecurity#419]
In ibmsecurity/isam/web/reverse_proxy/junctions_server.py add and set functions, the warnings variable does not have a default initialisation.
This means that any warnings will result in the functions failing unless warnings was passed as a parameter.
Previous versions had initialised warnings in the function parameters.

**Comment by tombosmansibm** [comment]
Thanks, will fix that.

**Comment by tombosmansibm** [comment]
The `add` function never had a proper initialization for warnings - good catch.

The `set` function has an initialization for warnings.
