### ISSUE TITLE
Container version 10.0.8.0 questions

### ISSUE THREAD

**Issue by daniew01** [IBM-Security/ibmsecurity#435]
Hi 

First Question:
I was wondering if these scripts/configs would work against ISAM Verify Access  as docker container [10.0.8.0] I have setup a test environment and trying to connect to my new container [docker-compose] file but are getting the following error. Making me think there is a compatability issue running these scripts against a container vs an appliance

"
  File "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages/ansible/template/__init__.py", line 1027, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: dict object has no element 0
fatal: [192.168.8.33]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: dict object has no element 0"
}
"

I am running everything on my Fedora laptop using podman 

Second Question:
We are planning to run the containers in k8 in Azure and is wondering if this will work for that environment eventually 

Kind Regards

**Comment by daniew01** [comment]
This is what is installed on my newly venv :

pipdeptree 
\Warning!!! Duplicate package metadata found:
"/home/daniew/workspace/python_Wspace/container/venv/lib/python3.12/site-packages"
  pip                              24.2             (using 24.2, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  resolvelib                       1.0.1            (using 1.0.1, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  appdirs                          1.4.4            (using 1.4.4, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  urllib3                          2.2.3            (using 2.2.3, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  six                              1.16.0           (using 1.16.0, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  PyYAML                           6.0.2            (using 6.0.2, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  pyparsing                        3.1.4            (using 3.1.4, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  pycparser                        2.22             (using 2.22, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  packaging                        24.1             (using 24.1, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  ordered-set                      4.1.0            (using 4.1.0, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  MarkupSafe                       2.1.5            (using 2.1.5, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  jmespath                         1.0.1            (using 1.0.1, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  idna                             3.10             (using 3.10, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  charset-normalizer               3.3.2            (using 3.3.2, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  certifi                          2024.8.30        (using 2024.8.30, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  requests                         2.32.3           (using 2.32.3, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  pipdeptree                       2.23.4           (using 2.23.4, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  Jinja2                           3.1.4            (using 3.1.4, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  cffi                             1.17.1           (using 1.17.1, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  ibmsecurity                      2024.9.30.0      (using 2024.9.30.0, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  cryptography                     43.0.1           (using 43.0.1, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  ansible-core                     2.17.4           (using 2.17.4, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
  ansible                          10.4.0           (using 10.4.0, "/home/daniew/workspace/python_Wspace/container/venv/lib64/python3.12/site-packages")
NOTE: This warning isn't a failure warning.
------------------------------------------------------------------------
ansible==10.4.0
└── ansible-core [required: ~=2.17.4, installed: 2.17.4]
    ├── cryptography [required: Any, installed: 43.0.1]
    │   └── cffi [required: >=1.12, installed: 1.17.1]
    │       └── pycparser [required: Any, installed: 2.22]
    ├── Jinja2 [required: >=3.0.0, installed: 3.1.4]
    │   └── MarkupSafe [required: >=2.0, installed: 2.1.5]
    ├── packaging [required: Any, installed: 24.1]
    ├── PyYAML [required: >=5.1, installed: 6.0.2]
    └── resolvelib [required: >=0.5.3,<1.1.0, installed: 1.0.1]
appdirs==1.4.4
ibmsecurity==2024.9.30.0
├── jmespath [required: >=1.0.0, installed: 1.0.1]
├── PyYAML [required: Any, installed: 6.0.2]
└── requests [required: Any, installed: 2.32.3]
    ├── certifi [required: >=2017.4.17, installed: 2024.8.30]
    ├── charset-normalizer [required: >=2,<4, installed: 3.3.2]
    ├── idna [required: >=2.5,<4, installed: 3.10]
    └── urllib3 [required: >=1.21.1,<3, installed: 2.2.3]
ordered-set==4.1.0
pipdeptree==2.23.4
├── packaging [required: >=24.1, installed: 24.1]
└── pip [required: >=24.2, installed: 24.2]
pyparsing==3.1.4
six==1.16.0

**Comment by tombosmansibm** [comment]
OK, this sounds like you are using an old version of the  ISAM ansible collection.  I don't know what a siteScript is, but I assume this runs Ansible playbooks.

I've quickly tried what I think you are doing, and that works fine.
````
 ansible-playbook -i inventories/local/ -l mytestmachine ibm.isam.report_fix_levels.yml 
````


Here is some more documentation: https://github.com/IBM-Security/isam-ansible-collection
A first step woud be to upgrade (or install) the ISAM ansible collection:
````
 ansible-galaxy collection install ibm.isam --force
````

Note that the old version of the Ansible integrations, isam-ansible-roles, is no longer supported.

**Comment by daniew01** [comment]
Thanx I got the above to work on my laptop.

I have created a new python venv example "test/venv" , changed into this folder , activate the virtual env , install and upgrade pip and installed ansible and ibmsecurity but the collection seems to be installed under <my home>.ansible folder and not in the virtual environment folder. 

Previously I would create the virtual env "old_test/venv", create an ansible.cfg file pointing to the roles subfolder , then would extract the roles.zip into roles subfolder  then activate ..... etc. 

I would crate a docker image from this virtual environment and use this as my automation container - It is possible with this new ansible-collection on should I move to ansible-navigator?

Or is there a way I can set everyting up in Azure using DevOps and their pipelines?

**Comment by tombosmansibm** [comment]
You should install collections into a collections/ directory inside your playbooks directory.

You can use a collections/requirements.yml file, with a list of your collections:

     ansible-galaxy collection install -r collections/requirements.yml --force -p ./collections

Alternatively, you can run this separately:

    ansible-galaxy collection install ibm.isam -p ./collections

You don't need specific settings in ansible.cfg for this to work in recent versions of ansible.

Collections have no direct link with the installation processes of Python code , so there is no direct link between a virtual environment and collections.  You do need to have ibmsecurity installed in your virtual environment, though.

If you use ansible-navigator, the collections you install locally (in your playbook directory) will be available automatically within the Container.  In AAP (Ansible Automation Platform), any collections in the collections/requirements.yml file will be installed into the Execution Environment automatically.

My recommendation is to use ansible-navigator with an Execution Environment, but nothing stops you using your own container solution.  However, I can't help you with that.
