### ISSUE TITLE
Importing ZIP into isam web management_root

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/ibmsecurity#45]
Hi,

Is there anyone having a sample working role (or python code) to import a zip file into isam web reverse proxy using the ibmsecurity/isam/web/reverse_proxy/management_root/all.py code?
We are obtaining the following message when running a role that leverages the ibmsecurity/isam/web/reverse_proxy/management_root/all.py code: 
[DEBUG] [ibmsecurity.appliance.ibmappliance] [invoke_post_files():151] Headers are: {'Accept': 'application/json,text/html,application/xhtml+xml,application/xml'}\n", "msg": "Error> action does not have the right set of arguments or there is a code bug! Options: isamAppliance=isam_server, force=False, instance_id=\"default\", filename=\"/home/somehome/isam_home/tmp/b2e_root.zip\"", "name": "ibmsecurity.isam.web.reverse_proxy.management_root.all.import_zip"}

Not totally sure if the error message is returned from appliance or from ibmsecurity module itself (2017.10.18.0)
We share our test role in attachment and this is how it is invoked from a play:
    - role: import_management_root_zip
      tags: ["web", "reverseproxy", "management root"]
      import_management_root_zip_instance_id: "default"
      import_management_root_zip_filename: "{{ ansible_env.ISAM_TMP }}/b2e_root.zip"
      when : ifc_add_network_ipv4_address_2 is defined

[import_management_root_zip.zip](https://github.com/IBM-Security/ibmsecurity/files/1431143/import_management_root_zip.zip)

Thanks

**Comment by ram-ibm** [comment]
Just realizing that this was never responded to - is this still can issue? If fixed - please post the solution and close it.

**Comment by sygilber** [comment]
Will close for now, and re-open when I have time to re-test.

**Comment by tombosmansibm** [comment]
This is still an issue
