### ISSUE TITLE
Helper to retrieve IP address uuid

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/ibmsecurity#48]
The current ibmsecurityisam.base.network.static_routes.py add() method expects as the table argument either the value “main” or the uuid of the IP for which to configure a new static route.

Since there is no helper method available in code ibmsecurityisam.base.network.interfaces.py to retrieve the uuid of a particular configured IPV4 address, I find it is very difficult to implement a playbook to configure a new static route for a specific “table” or IP, other than the “main” table.

The current role add_static_route forces me to know already the uuid for the corresponding IPv4 which I do not have available.

So I am thinking that we need a new helper method in ibmsecurityisam.base.network.interfaces.py with signature like _get_ipv4_address_uuid(isamAppliance, label, address, vlanId=None, check_mode=False, force=False) or even just _get_ipv4_address_uuid(isamAppliance, address, check_mode=False, force=False) that will look up and convert to the uuid form the IPv4 address passed in argument. 

The equivalent IPv6 version of the method could be provided after for sake of completeness.

Any thought? Any other way to achieve my goal that I could have overlooked ?

Thanks

**Comment by sygilber** [comment]
I was thinking of something like this helper added to ibmsecurity/isam/base/network/interfaces.py:

def get_ipv4_address_uuid(isamAppliance, address, check_mode=False, force=False):
    """
    Retrieving uuid for an ipv4 address
    """
    ret_obj = get_all(isamAppliance)
    ipv4_address_uuid = None

    for intfc in ret_obj['data']['interfaces']:
        for adds in intfc['ipv4']['addresses']:
            if adds['address'] == address:
                ipv4_address_uuid = adds['uuid']
                break

    return ipv4_address_uuid

**Comment by ram-ibm** [comment]
I admit to using the "main" table exclusively - so have not dealt with non-main situations. I think this calls for a search() function. I will need to look into this a bit more (the JSON data for interfaces is too complex for me to remember off the top of my head). The code you has posted looks like it would do the trick - except i would call the function search().

**Comment by sygilber** [comment]
https://github.com/IBM-Security/ibmsecurity/commit/a7ffe07c6761417574ff737e9859c8a7e8ed6866

Thanks
