### ISSUE TITLE
All lights green running playbook with authentication error

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/ibmsecurity#49]
When the remote user registry account (for instance in Active Directory configured with the switch_auth role) being used to connect and administer the appliance is in "locked" state, the LMI will not let the user "in". This is expected.

But when the same locked account tries to connect to the rest-api with the ibmsecurity/ansible/roles software stack, the account locked status is not recognized, and everything seems to proceed fine. No change are reported while running playbook ... but you know you are running a playbook that was supposed to propagate tones of changes ... what is going on ? 
What triggered me on a lead was this message  following:

` [WARNING]: API invoked requires module: ['wga'], appliance has no modules active`

Why am I getting this? All activation modules and license support file are installed. The truth is that the appliance is not able truly to authenticate you in and Ansible is therefore not able to retrieve all facts it should be getting. But the behavior of the playbook is really running all "lights green" ...
This is not the first time I stumbled into this situation but the first time that I understand what is going on.

So maybe we need some logic added either in the restapi appliance side? or ibmsecurity stack to recognize the failed locked out situation and trigger an exception to alt everything there.

**Comment by sygilber** [comment]
Did some more diging and I can see the following with -vvv on:

[2017-12-15 20:29:55,392] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.user.applianceuser] [__init__():9] Creating a user\n
[2017-12-15 20:29:55,392] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.user.user] [__init__():8] Creating a user\n
[2017-12-15 20:29:55,392] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.isamappliance] [__init__():13] Creating an ISAMAppliance\n
[2017-12-15 20:29:55,392] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [__init__():15] Creating an IBMAppliance\n
[2017-12-15 20:29:55,392] [PID:21972 TID:139658664892224] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieving firmware ***\n
[2017-12-15 20:29:55,392] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():92] Checking for minimum version: None.\n
[2017-12-15 20:29:55,393] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():108] Checking for one of required modules: None.\n
[2017-12-15 20:29:55,393] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():125] Warnings: []\n
[2017-12-15 20:29:55,393] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():301] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n
[2017-12-15 20:29:55,393] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():306] Input Data: {}\n
[2017-12-15 20:29:55,393] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():35] Suppressing SSL Warnings.\n
[2017-12-15 20:29:55,393] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():24] Issuing request to: https://stha9n0fx.iad.ca.inet:443/firmware_settings\n
[2017-12-15 20:29:55,395] [PID:21972 TID:139658664892224] [DEBUG] [urllib3.connectionpool] [_new_conn():824] Starting new HTTPS connection (1): stha9n0fx.iad.ca.inet\n
[2017-12-15 20:29:55,655] [PID:21972 TID:139658664892224] [DEBUG] [urllib3.connectionpool] [_make_request():396] https://stha9n0fx.iad.ca.inet:443 \"GET /firmware_settings HTTP/1.1\" 403 None\n
[2017-12-15 20:29:55,657] [PID:21972 TID:139658664892224] [ERROR] [ibmsecurity.appliance.ibmappliance] [_process_response():46]   Request failed: \n
[2017-12-15 20:29:55,657] [PID:21972 TID:139658664892224] [ERROR] [ibmsecurity.appliance.ibmappliance] [_process_response():47]      status code: 403\n
[2017-12-15 20:29:55,657] [PID:21972 TID:139658664892224] [ERROR] [ibmsecurity.appliance.ibmappliance] [_process_response():49]      text: Error 403: AuthenticationFailed\n\n
[2017-12-15 20:29:55,658] [PID:21972 TID:139658664892224] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieving a specific configuration entry - Reverse Proxy ***\n
[2017-12-15 20:29:55,658] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():92] Checking for minimum version: None.\n
[2017-12-15 20:29:55,658] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():103] Detected module: ['wga'] from uri: /wga/reverseproxy/default/configuration/stanza/local-response-redirect/entry_name/local-response-redirect-uri.\n
[2017-12-15 20:29:55,658] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():108] Checking for one of required modules: ['wga'].\n
[2017-12-15 20:29:55,658] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():125] Warnings: [\"API invoked requires module: ['wga'], appliance has no modules active.\"]\n
[2017-12-15 20:29:55,659] [PID:21972 TID:139658664892224] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Updating a configuration entry or entries by stanza - Reverse Proxy ***\n
[2017-12-15 20:29:55,659] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():92] Checking for minimum version: None.\n
[2017-12-15 20:29:55,659] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():103] Detected module: ['wga'] from uri: /wga/reverseproxy/default/configuration/stanza/local-response-redirect/entry_name/local-response-redirect-uri.\n
[2017-12-15 20:29:55,659] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():108] Checking for one of required modules: ['wga'].\n
[2017-12-15 20:29:55,659] [PID:21972 TID:139658664892224] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():125] Warnings: [\"API invoked requires module: ['wga'], appliance has no modules active.\"]

Where we can clearly see the "403" authentication result code obtained but despite that the execution continues.

Probably not so much an issue specific to only locked account .. maybe also just bad password (yes just confirmed using an invalid account/password).

Is it possible that this except clause below silently ignores the previous authn error in isamappliance.py ? get_facts() invokves get_version() which in turns invokes get_firmware() where errors happens first.

```
    def get_facts(self):
        """
        Get facts about the appliance
        """
        # Fact collection will abort on any exception
        try:
            self.get_version()

            # Check if appliance is setup before collecting Activation information
            import ibmsecurity.isam.base.setup_complete
            ret_obj = ibmsecurity.isam.base.setup_complete.get(self)
            if ret_obj['data'].get('configured') is True:
                self.get_activations()
        # Exceptions like those connection related will be ignored
        except:
            pass
```

**Comment by ram-ibm** [comment]
The get facts was designed to collect data and not deal with connection or auth failures. It also determines what modules are active on the appliance. When it comes time to run an actual REST API the modules are checked before execution. The idea was not to provide warnings but not errors as much as possible.

Maybe we need to re-look at the auth error differently and stop execution for that. Let me see what I can do.

Please note that the problem here is one of knowing what the issue is - userid is invalid - rather than the framework working wrong.

**Comment by sygilber** [comment]
I believe i tested both with valid and locked account, with invalid account, and valid account with wrong password (that become locked by sole fact of running once the playbook). 

The things is that a single occurrence of running a playbook with a wrong  password will most probably end up locking the account in the remote registry for that user despite he tried only once to log-in, the ansible module attempts behind the scene numerous rest call for all various prep work before the main « user » tasks in the playbook. Depending on the security policy implemented in the corporate remote user registry, the fail login attempts generated under the cover will or not lock the account. 


The false sense of all play tasks show as green is maybe a greather risk here as you think that you achieved a desire state but you did not. For the less savvy operator, it will not get noticed. 


That all being said, now that this is understood, we do not need to rush in some code in there. Lets take the time to test any remediation to ensure that it does not break other areas. 

Last evening, i tested various scenarios using curl cmd to query admin_cfg end-point (locked account, invalid account or wrong password) and in all cases i had obtained the 403 return code. 

Thanks

**Comment by ram-ibm** [comment]
I think it is possible to throw an exception even while gathering facts - when we get an authentication failure. Will need to test it out. Will need to tackle this in the new year.

**Comment by sygilber** [comment]
Hi, I am slowly putting back time on this issue. I will reports on various test and results observed as we go. Please never consider the last test performed as a candidate solution. It is just sharing some results/observations from testing some concepts.

First (very brutal) approach tested: just commenting out the "try/except/pass" code in the method get_facts of isamappliance.py. 

So this block:
```
    def get_facts(self):
        """
        Get facts about the appliance
        """
        # Fact collection will abort on any exception
        try:
            self.get_version()

            # Check if appliance is setup before collecting Activation information
            import ibmsecurity.isam.base.setup_complete
            ret_obj = ibmsecurity.isam.base.setup_complete.get(self)
            if ret_obj['data'].get('configured') is True:
                self.get_activations()
        # Exceptions like those connection related will be ignored
        except:
            pass
```

becomes more like this:

```
    def get_facts(self):
        """
        Get facts about the appliance
        """
        # Fact collection will abort on any exception
        self.get_version()

        # Check if appliance is setup before collecting Activation information
        import ibmsecurity.isam.base.setup_complete
        ret_obj = ibmsecurity.isam.base.setup_complete.get(self)
        if ret_obj['data'].get('configured') is True:
            self.get_activations()

```
The goal was to see if simply letting the exception percolate up the call stack would results in an immediate halt of the playbook (still with the idea of preventing silent account locking). It did the trick but it is not nice output for the Ansible user. It behaves as if a programming or system error occurred. We don’t want the Ansible playbook user to experience such raw system Ansible error type.

The results was:

```
TASK [create_snapshot : Snapshot of Appliance] *************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ibmsecurity.appliance.ibmappliance.IBMError: ('HTTP Return code: 403', u'Error 403: AuthenticationFailed\n')
fatal: [someserver]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_av0EFn/ansible_module_isam.py\", line 160, in <module>\n    main()\n  File \"/tmp/ansible_av0EFn/ansible_module_isam.py\", line 97, in main\n    isam_server = ISAMAppliance(hostname=appliance, user=u, lmi_port=lmi_port)\n  File \"/home/someuser/isam_home/modules/utilities-python/src/ibmsecurity/ibmsecurity/appliance/isamappliance.py\", line 19, in __init__\n    IBMAppliance.__init__(self, hostname, user)\n  File \"/home/someuser/isam_home/modules/utilities-python/src/ibmsecurity/ibmsecurity/appliance/ibmappliance.py\", line 52, in __init__\n    self.get_facts()\n  File \"/home/someuser/isam_home/modules/utilities-python/src/ibmsecurity/ibmsecurity/appliance/isamappliance.py\", line 511, in get_facts\n    ret_obj = ibmsecurity.isam.base.setup_complete.get(self)\n  File \"/home/someuser/isam_home/modules/utilities-python/src/ibmsecurity/ibmsecurity/isam/base/setup_complete.py\", line 12, in get\n    \"/setup_complete\")\n  File \"/home/someuser/isam_home/modules/utilities-python/src/ibmsecurity/ibmsecurity/appliance/isamappliance.py\", line 406, in invoke_get\n    requires_version=requires_version, warnings=warnings)\n  File \"/home/someuser/isam_home/modules/utilities-python/src/ibmsecurity/ibmsecurity/appliance/isamappliance.py\", line 323, in _invoke_request\n    self._process_response(return_obj=return_obj, http_response=r, ignore_error=ignore_error)\n  File \"/home/someuser/isam_home/modules/utilities-python/src/ibmsecurity/ibmsecurity/appliance/isamappliance.py\", line 51, in _process_response\n    raise IBMError(\"HTTP Return code: {0}\".format(http_response.status_code), http_response.text)\nibmsecurity.appliance.ibmappliance.IBMError: ('HTTP Return code: 403', u'Error 403: AuthenticationFailed\\n')\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

Any how, this approach is for sure not the best one out there as any exception would completely halt the whole playbook on any exception type, even when a single server in the inventory does not respond (connection error).

The next approaches I am considering are:

-Whenever an exception is catched in the method get_facts() we could parse the error text to detect the presence of the 403 AuthenticationFailed msg, and act accordingly: somehow halt the playbook (rc=403) or let it resume for other type of non-fatal exception.
-or write a new IBMAuthNErrror which specialized in Authentication error (http 403 for instance) and thus it would be easier in the code to trap specifically this exception type to modify the behavior.
-Write a new IBMFatal exception that anyone can use when raising an exception that we consider severe enough to force the playbook to halt completely. But I believe it should always be up to the one calling the Try/Except block to decide that is fatal or not.

Any comments of the option we should be looking/testing next?

I am currenlty analyzing in the code when we are getting HTTP return code back frmo get/post if this is also the right time to detect the 403 condition and act right way on this condition.

**Comment by ram-ibm** [comment]
It might be best to throw exception when the HTTP request is being made - that we way we do not make an assumption on the first call. Then we may need to catch the exception in the Ansible custom module.

Will need a fair bit of testing. Want to hold off until there is time for it.

**Comment by juttlaing** [comment]
We are having the same problem, but in our case with ISAM pointing to AD, there is a problem when ISAM performs the LDAPS TLS 1.2 handshake to AD (due to problem on the windows AD server).   Ad intermittently returns a server_hello to isam with a zero byte tcp packet (invalid server_hello) and the handshake doesn't complete.  The ISAM ldap client times out after 5 seconds and sends a FIN to AD, and the connection is attempted again, over and over, until AD returns a valid server_hello.  The problem at AD (not responding with a valid server_hello) continues for 10 seconds.

What we see at the ibmsecurity api (used via python scripts verses playbooks) is that in this condition, is the same thing described above.  The API does the time/date rest call and component rest/call and returns 403: AuthenticationFailed, however the api function IBMError doesn't catch this an an exception and lets processing continue (as if everything is ok).

Strangely enough, the ibmsecurity api IBMError function picks up the "typical" error conditions related to using external LDAP such as:
1. bad LMI (AD) user credentials
2. can't communicate to AD at all
3. authorization problem due to AD user not in AD group role mapped to ISAM ADMIN group

In these conditions, the same 403: AuthenticationError   or   403: you do not have permissions     is caught in python as an exception via IBMError.

Obviously the problem needs to be fixed at AD, and packet traces confirm AD is the issue.  But the problem is intermittent and it has been going on for 2 months (good ole microsoft).  This problem has rendered every script I've written using the ibmsecurity api useless.  None of them complete, and there isn't a way to catch this condition due to the isamappliance.py mobule and IBMError not catching the problem.  Very strange.

Any updates on potential fixes within this module?  It is required for every function in the api since each REST call is authenticated.  Just wondering - again we are trying to rectify the problem at AD.  I just find it strange the same rc and errortext are returned yet in this condition the api doesn't "catch" the problem.

**Comment by sygilber** [comment]
Hi

Are you using a load-balancer in front of your AD for HA ? Sometime this helps « condition » the TLS handshakes to a more uniform pattern, from the point of view of the calling application (in this explicit case the ISAM appliance). 

This is interesting because that i started to look into the ibmsecurity code this morning again after letting this issue rest for some months now. 

Can we first have a crystal clear description of the behavior ? Even my own interpretation when i originally opened this issue back in 2017 was biased by various conditions i would observed. 

I believe i had narrowed the story to a very simpler one : just try to run playbooks using invalid account (either local or remote in AD). In fact, the only difference in behavior with a remote AD account is that you risk locking the remote AD account depending on the locking security policy configured on the remote AD. 

So for simplifying this story, i believe testing with either an invalid remote account or just an invalid local LMI account should be sufficient. 

For now, this is what this story (or issue)  is about. Communications/TLS issues are a slightly different topic that can be addressed later. 

Please let us know if at all possible condition/behavior you get. 

Thanks

**Comment by sygilber** [comment]
I have some "lab/concept" code shared here: https://github.com/sygilber/ibmsecurity/tree/issue_49

It is not meant for taking into your environment, it will not be supported.
It is only meant to allow folks to have a peek at it.

What it does is that it raises a new type of exception called IBMFatal if a HTTP 403 is returned from the appliance. 

Can we find a better name for the exception ? I just did not want it to specialize it too much so it can be re-used in other absolutely "fatal" scenarios that could arise some day.

IBMFatal is catched and re-thrown unconditionnally in a few spot that tend to generate numerous successive behind the scene "connection" attempts .

It does not produce a nice output but it does stop short the playbook execution as soon as a single an 403 is returned. 

So this is an improvement already except for the output which is less usually in Ansible playbooks.

> TASK [some_role : Execute some step] **************************************************
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ibmsecurity.appliance.ibmappliance.IBMFatal: ('HTTP Return code: 403', u'Error 403: AuthenticationFailed\n')
> fatal: [stha9n0fw.iad.ca.inet]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_V8fVCA/ansible_module_isam.py\", line 160, in <module>\n    main()\n  File \"/tmp/ansible_V8fVCA/ansible_module_isam.py\", line 97, in main\n    isam_server = ISAMAppliance(hostname=appliance, user=u, lmi_port=lmi_port)\n  File \"/home/somehome/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/appliance/isamappliance.py\", line 20, in __init__\n    IBMAppliance.__init__(self, hostname, user)\n  File \"/home/somehome/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/appliance/ibmappliance.py\", line 56, in __init__\n    self.get_facts()\n  File \"/home/somehome/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/appliance/isamappliance.py\", line 525, in get_facts\n    self.get_version()\n  File \"/home/somehome/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/appliance/isamappliance.py\", line 550, in get_version\n    ret_obj = ibmsecurity.isam.base.version.get(self)\n  File \"/home/somehome/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/isam/base/version.py\", line 12, in get\n    \"/core/sys/versions\")\n  File \"/home/somehome/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/appliance/isamappliance.py\", line 418, in invoke_get\n    requires_version=requires_version, warnings=warnings)\n  File \"/home/somehome/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/appliance/isamappliance.py\", line 335, in _invoke_request\n    self._process_response(return_obj=return_obj, http_response=r, ignore_error=ignore_error)\n  File \"/home/somehome/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/appliance/isamappliance.py\", line 52, in _process_response\n    raise IBMFatal(\"HTTP Return code: {0}\".format(http_response.status_code), http_response.text)\nibmsecurity.appliance.ibmappliance.IBMFatal: ('HTTP Return code: 403', u'Error 403: AuthenticationFailed\\n')\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
> 
> PLAY RECAP *************************************************************************************************************************************************************
> localhost                  : ok=11   changed=0    unreachable=0    failed=0
> stha9n0fw.iad.ca.inet      : ok=4    changed=0    unreachable=0    failed=1
> 

I did not research yet if it is possible to make the exception look more like a "managed" one, with less traceback.

**Comment by sygilber** [comment]
After investigating a bit on how we could make the [Task] completion display a status that is less intimidating that the previous experiment results, I am finding that we could opt to perform some code adjustments in the start_config/library/isam.py module by catching explicitly the IBMFatal exception to change the behavior. But the more I think of it, this is icing on the cake for now; the real issue we are aiming at resolving here is the authentication error not getting enough attention when a playbook runs. We will look at starting to use on a larger scale yesterday's "exploratory" code to see how it behaves. Maybe after a week of using it, I may consider submitting a PR.

**Comment by juttlaing** [comment]
So first I appreciate your insight, and agree with your approach on the IBMFatal.

I don't want to get bogged down with the actual issue I'm experiencing related to AD, we know it is a problem with the AD controller responding with bad server_hello packets to ISAM intermittently.  We don't use a load balancer, just DNS A record pointing to 3 AD DCs.

The issue I'm reporting is related to how the ibmsecurity api is handling 403 errors.

If you have a 403, that's it, the rest call has failed.

In my case I'm not using playbooks, I'm using a python script that utilizes the ibmsecurity api.  I'm very versed in python, and have dug into the ibmsecurity api, and its an incredible job all around if you don't mind me saying so!  I use it to its fullest.

In my script I basically have a try/except block that is a FUNCTION that can make any REST call in the api (I just pass the api call as a function parameter).  The except block catches IBMError.  I (like the api code) extract the responsecode (rc) and errortext from the exception stack, evaluate the responsecode, and decide what to do based on the response code.  Certain responsecodes I raise exceptions for, others I do not.

What I noticed is, when any rest call using the ibmsecurity api tries to check the time/date, licensing/components (get_facts, etc), if an IBMError is caught in the api the exception isn't raised.  Then I noticed your comment above under the get_facts function and realized, that is my issue.  Remming out the --> Except: pass --> in the get_facts exception block is the answer.

When the api does these initial calls, if there is a 403, obviously the rest call is going to fail because of one of these possible scenarios when using an external LDAP like AD:
1. ad account is locked
2. ISAM can't communicate to AD (network issue)
3. bad credentials
4. User authenticated however not in proper AD group (authorization error)

Specifically during my AD ldap handshake issue, resulting in a 403, the get_Facts was not raising the exception, and now I know why.

So your thoughts above are perfect.  You are basically adding more exception handling for various conditions such as 403, 500, etc that are caught as exceptions, whether it is a get_facts rest call OR the actual rest call the script or playbook is making.  I feel the IBMFatal addition is the way forward in the long term, and the short term approach is also a good test bed.

For now I simply remmed the statements per your 04/13/2018 comment.

I look forward to seeing these changes.

On a side note, I added some basic code to my own scripts that use the api when IBMError is caught in my Except block that gives the user an additional "user friendly" text based on response code, though the errors returned by the appliance in these conditions are pretty clear:
Except IBMError as e:
    if rc in ("400"):
        text = "bad OR malformed request"
    elif rc in ("401"):
        text = "unauthorized due to missing WWW-Authenticate header"
    elif rc in ("403"):
        text = "lmi authentication failed  OR  isam host permissions issue"
    elif rc in ("404"):
        text = "url requested not found"
    elif rc in ("405"):
        text = "http method not allowed"
    elif rc in ("408"):
        text = "request timed out"
    elif rc in ("500"):
        text = "internal server error"
    elif rc in ("502"):
        text = "bad gateway OR could not establish connection to isam host"
    elif rc in ("503"):
        text = "service unavailable due to temporary overloading OR maintenance"
    elif rc in ("505"):
        text = "http version not supported"
    else:
        text = "unknown error making rest call to isam host ip"

And again, superb job on all of the python scripting to date!  Appreciate your feedback.

**Comment by sygilber** [comment]
Hi

Anyone interested in testing the patch that i submitted in PR AuthN Error ? It is rather small as it requires one to copy only 2 python file over the latest available ibmsecurity code. 

Thanks

**Comment by juttlaing** [comment]
I'll test it early next week!  Send me link to download or zip up and email directly (but email gateway may strip it).

**Comment by sygilber** [comment]
Hi, you can just pull these 2 sources:

https://github.com/sygilber/ibmsecurity/blob/issue_49/ibmsecurity/appliance/ibmappliance.py
https://github.com/sygilber/ibmsecurity/blob/issue_49/ibmsecurity/appliance/isamappliance.py

Again, even if it does work for you, this is an unofficial patch which may or not be accepted/merged by the Git master for the "ibmsecurity" project. But it will give us some early feedback about its vialibilily.

Thanks

**Comment by sygilber** [comment]
Resolved by https://github.com/IBM-Security/ibmsecurity/pull/121
