### ISSUE TITLE
Call to set from web\runtime\configuration\entry.py appends instead of replacing (if space in attribute)

### ISSUE THREAD

**Issue by LouBea** [IBM-Security/ibmsecurity#54]
Hi,

We have a call to the set function of "ibmsecurity\isam\web\runtime\configuration\entry.py" through a role called set_runtime_conf

Here is the task/main of the set_runtime_conf role:

```
- name: Configure Runtime stanza(s) entries (Set)
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.web.runtime.configuration.entry.set
    isamapi:
      resource_id : "{{ item.resource_id }}"
      stanza_id:    "{{ item.stanza_id }}"
      entries:      "{{ item.entries }}"
  with_items:       "{{ set_runtime_conf_entries }}"
  when: set_runtime_conf_entries is defined
  notify:
  - Commit Changes
  - Restart Web Runtime
```
  
When the existing attribute contains a space the new value is appended instead of deleted.

For example, if I run a simple test : replace "test = a_a" by "test = a_b" it works:

```
Before:

[aznapi-configuration]
test = a_a

run:

    - role: set_runtime_conf
      tags: ["ISAM_PS", "baseline", "ivmgrd.conf"]
      set_runtime_conf_entries:
        - { resource_id: "ivmgrd.conf", stanza_id: "aznapi-configuration", entries: "[['test','a_b']]" }
        
After:

[aznapi-configuration]
test = a_b
```

Similarly replacing "test = a_a" by "test = a b" works:

```
Before:

[aznapi-configuration]
test = a_a

run:

    - role: set_runtime_conf
      tags: ["ISAM_PS", "baseline", "ivmgrd.conf"]
      set_runtime_conf_entries:
        - { resource_id: "ivmgrd.conf", stanza_id: "aznapi-configuration", entries: "[['test','a b']]" }
        
After:
        
[aznapi-configuration]
test = a b
```

BUT replacing "test = a a" by "test = a_b" does NOT works, the new value is appended instead of replaced.

```
Before:

[aznapi-configuration]
test = a a

run:

    - role: set_runtime_conf
      tags: ["ISAM_PS", "baseline", "ivmgrd.conf"]
      set_runtime_conf_entries:
        - { resource_id: "ivmgrd.conf", stanza_id: "aznapi-configuration", entries: "[['test','a_b']]" }
        
After:
                
[aznapi-configuration]
test = a a
test = a_b
```

Similarly replacing "test = a a" by "test = a b" does NOT works, the new value is appended instead of replaced.

```
Before:

[aznapi-configuration]
test = a a

run:

    - role: set_runtime_conf
      tags: ["ISAM_PS", "baseline", "ivmgrd.conf"]
      set_runtime_conf_entries:
        - { resource_id: "ivmgrd.conf", stanza_id: "aznapi-configuration", entries: "[['test','a b']]" }
        
After:
                
[aznapi-configuration]
test = a a
test = a b
```

finally "replacing" the attribute "test = a a" by the same value "test = a a" does works. Idempotence ok, playbook detected no change & did not act.

Thanks for your help,
Louis

**Comment by LouBea** [comment]
I will reformulate this issue

**Comment by ram-ibm** [comment]
Deleting entry, will be re-added: ivmgrd.conf/aznapi-configuration/logcfg/audit.azn:rsyslog server=1.2.3.4,port=12346,log_id=sandbox.rt-audit,flush_interval=20,max_event_len=100,rebind_retry=3,queue_size=0,hi_water=1,error_retry=2

I had seen a similar issue which was resolved when I encoded the URI to be called for the delete. Do you want to post some other information - or should I try to resolve it with what you posted?

**Comment by ram-ibm** [comment]
Do you have the latest code? I see there is logic to encode the URL being send for deletion.

```
            # URL being encoded primarily to handle request-log-format that has "%" values in them
            f_uri = "{0}/{1}/configuration/stanza/{2}/entry_name/{3}/value/{4}".format(uri, reverseproxy_id,
                                                                                          stanza_id, entry_id, value_id)
            # Replace % with %25 if it is not encoded already
            import re
            ruri = re.sub("%(?![0-9a-fA-F]{2})", "%25", f_uri)
            # URL encode
            import urllib
            full_uri = urllib.quote(ruri)
            return isamAppliance.invoke_delete(
                "Deleting a value from a configuration entry - Reverse Proxy", full_uri)
```

**Comment by LouBea** [comment]
I changed the description & title to pinpoint the issue. Thanks in advance for your help.

**Comment by ram-ibm** [comment]
I checked the code and there is logic to encode the delete uri - which I dont see happening in your trace. Are you sure you have the latest python package?

**Comment by ram-ibm** [comment]
https://github.com/IBM-Security/ibmsecurity/blob/master/ibmsecurity/isam/web/reverse_proxy/configuration/entry.py

Line#161 I see encoding... there is very similar code between web runtime (policy server) config changes and WebSEAL (reverse proxy) config changes.

**Comment by LouBea** [comment]
Hi Ram,

To test this I copied the encoding lines from the delete function in "ibmsecurity/isam/web/reverse_proxy/configuration/entry.py" to the delete function in our "ibmsecurity/isam/web/runtime/configuration/entry.py" and re-tested but that did not fix the issue. If the attribute value has a space in it, it is still added(duplicated) instead of replaced.

Regards,
Louis

**Comment by ram-ibm** [comment]
Ah so I was mixing up the runtime with reverseproxy code. I see the issue now - let me see how it can be fixed.

**Comment by sygilber** [comment]
Ram, for your information, we have observed that the function 'ibmsecurity.isam.web.reverse_proxy.configuration.entry.set' behaves similarly. If the line to replace containes a values with a space " " then a new line is appended.

**Comment by ram-ibm** [comment]
Okay thanks for the update - I am checking to see how to solve this. My solutions so far have not worked.

**Comment by ram-ibm** [comment]
I am unable to come up with valid values in the configuration that contain a space - hoping you have a valid scenario please?

**Comment by sygilber** [comment]
Here is a valid sample:
[aznapi-configuration]
logcfg = audit:rsyslog error_retry=2,path=rsyslog.cache,
rebind_retry=600,server=timelord,port=514,log_id=webseal-instance

Where there is a required space after rsyslog. This is just a sample. There are many variation on this.

**Comment by sygilber** [comment]
For more on this topic:

https://www.ibm.com/support/knowledgecenter/en/SSPREK_9.0.3.1/com.ibm.isam.doc/audit_web/task/tsk_send_to_rmt_syslog_svr.html

**Comment by ram-ibm** [comment]
I tested the reverse proxy configuration file updates / deletes and it works. I have been using logcfg with spaces so it has been working for a while - though I just reconfirmed.

The web runtime - I need to figure out a workaround that fits into the framework. Are there situations that require a space in, say, the ivmgrf.conf file?

**Comment by ram-ibm** [comment]
I added delete_all() functions - it is in lab branch. This could be leveraged to remove all entries and add them afresh, will work regardless of spaces. I am still trying to see how to handle when there are spaces.

**Comment by LouBea** [comment]
I retested this issue with the latest code and the problem as described originally id fixed. I will close the issue.

Thanks for your help.
Louis
