### ISSUE TITLE
Commit handler skipped after config_policyserver

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/ibmsecurity#56]
Hi,

For now, I am unsure if the issue is to be reported against the role or the ibmsecurity module, we can determine that later.

While testing and re-building from 9.04 factory image this week (using the 'lab' branch) on 2 different set of environments, we obtained a behavior I could not see before.

This is our playbook sequence which is pretty classic when initializing the policy server Appliance and promoting it as the primary cluster role:

    - role: config_policyserver
    - role: set_cluster_config
    - role: set_runtime_replication
    - role: export_cluster_sign

This is what happened:

    - role: config_policyserver (OK)
    - role: set_cluster_config (OK)
    - role: set_runtime_replication (OK)
    - role: export_cluster_sign (ERROR)
    
    *********  WGAWA0389E *********
    
    I then logged-in the LMI, discovered there were pending changes, commited them, waited to LMI to complete restart sequence, and relaunched the playbook and then export_cluster_sign role succeeded.
    
    - role: export_cluster_sign (OK)

The detailled trace:

> TASK [config_policyserver : Snapshot Appliance Before Configuring Policy Server] ***************************************************************************************
> changed: [someserver]
> 
> TASK [config_policyserver : Configure Local Policy Server using Embedded LDAP] *****************************************************************************************
> changed: [someserver]
> 
> TASK [config_policyserver : Update Connection Inactivity to be less than infinity] *************************************************************************************
> changed: [someserver]
> 
> TASK [set_cluster_config : Snapshot Appliance Before Configuring Cluster] **********************************************************************************************
> changed: [someserver]
> 
> TASK [set_cluster_config : Set Cluster Configuration] ******************************************************************************************************************
> changed: [someserver]
> 
> RUNNING HANDLER [start_config : Commit Changes] ************************************************************************************************************************
> skipping: [someserver]
> 
> RUNNING HANDLER [start_config : Restart Web Runtime] *******************************************************************************************************************
> skipping: [someserver]
> 
> TASK [set_runtime_replication : Set Web Runtime Replication Status in a cluster] ***************************************************************************************
> changed: [someserver]
> 
> TASK [export_cluster_sign : Export cluster signature from Primary appliance] *******************************************************************************************
> fatal: [someserver]: FAILED! => {"changed": false, "failed": true, "log": "[2018-01-26 17:22:15,391] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.user.applianceuser] [__init__():9] Creating a user\n[2018-01-26 17:22:15,392] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.user.user] [__init__():8] Creating a user\n[2018-01-26 17:22:15,392] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.isamappliance] [__init__():13] Creating an ISAMAppliance\n[2018-01-26 17:22:15,392] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [__init__():46] Creating an IBMAppliance\n[2018-01-26 17:22:15,393] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_request():575] Request: GET /core/sys/versions desc=Retrieving version\n[2018-01-26 17:22:15,393] [PID:56043 TID:139764347021120] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieving version ***\n[2018-01-26 17:22:15,393] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():92] Checking for minimum version: None.\n[2018-01-26 17:22:15,393] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():108] Checking for one of required modules: None.\n[2018-01-26 17:22:15,393] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():125] Warnings: []\n[2018-01-26 17:22:15,393] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():301] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n[2018-01-26 17:22:15,393] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():306] Input Data: {}\n[2018-01-26 17:22:15,393] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():35] Suppressing SSL Warnings.\n[2018-01-26 17:22:15,393] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():24] Issuing request to: https://someserver:443/core/sys/versions\n[2018-01-26 17:22:15,395] [PID:56043 TID:139764347021120] [DEBUG] [urllib3.connectionpool] [_new_conn():824] Starting new HTTPS connection (1): someserver\n[2018-01-26 17:22:15,741] [PID:56043 TID:139764347021120] [DEBUG] [urllib3.connectionpool] [_make_request():396] https://someserver:443 \"GET /core/sys/versions HTTP/1.1\" 200 None\n[2018-01-26 17:22:15,745] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():63] Status Code: 200\n[2018-01-26 17:22:15,745] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():65] Text: {\"firmware_label\":\"isam_9.0.4.0_20171201-2325\",\"firmware_build\":\"20171201-2325\",\"firmware_version\":\"9.0.4.0\",\"product_description\":\"IBM Security Access Manager\",\"deployment_model\":\"Appliance\",\"product_name\":\"isam\"}\n[2018-01-26 17:22:15,745] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_response():579] Response: 0\n[2018-01-26 17:22:15,745] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_request():575] Request: GET /setup_complete desc=Get Setup Complete Settings\n[2018-01-26 17:22:15,746] [PID:56043 TID:139764347021120] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Get Setup Complete Settings ***\n[2018-01-26 17:22:15,746] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():92] Checking for minimum version: None.\n[2018-01-26 17:22:15,746] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():108] Checking for one of required modules: None.\n[2018-01-26 17:22:15,746] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():125] Warnings: []\n[2018-01-26 17:22:15,746] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():301] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n[2018-01-26 17:22:15,746] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():306] Input Data: {}\n[2018-01-26 17:22:15,746] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():35] Suppressing SSL Warnings.\n[2018-01-26 17:22:15,746] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():24] Issuing request to: https://someserver:443/setup_complete\n[2018-01-26 17:22:15,747] [PID:56043 TID:139764347021120] [DEBUG] [urllib3.connectionpool] [_new_conn():824] Starting new HTTPS connection (1): someserver\n[2018-01-26 17:22:16,094] [PID:56043 TID:139764347021120] [DEBUG] [urllib3.connectionpool] [_make_request():396] https://someserver:443 \"GET /setup_complete HTTP/1.1\" 200 21\n[2018-01-26 17:22:16,097] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():63] Status Code: 200\n[2018-01-26 17:22:16,097] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():65] Text: { \"configured\": true}\n[2018-01-26 17:22:16,097] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_response():579] Response: 0\n[2018-01-26 17:22:16,098] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_request():575] Request: GET /isam/capabilities/v1 desc=Retrieving activations\n[2018-01-26 17:22:16,098] [PID:56043 TID:139764347021120] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieving activations ***\n[2018-01-26 17:22:16,098] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():92] Checking for minimum version: None.\n[2018-01-26 17:22:16,098] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():108] Checking for one of required modules: None.\n[2018-01-26 17:22:16,098] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():125] Warnings: []\n[2018-01-26 17:22:16,098] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():301] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n[2018-01-26 17:22:16,098] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():306] Input Data: {}\n[2018-01-26 17:22:16,098] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():35] Suppressing SSL Warnings.\n[2018-01-26 17:22:16,098] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():24] Issuing request to: https://someserver:443/isam/capabilities/v1\n[2018-01-26 17:22:16,099] [PID:56043 TID:139764347021120] [DEBUG] [urllib3.connectionpool] [_new_conn():824] Starting new HTTPS connection (1): someserver\n[2018-01-26 17:22:16,455] [PID:56043 TID:139764347021120] [DEBUG] [urllib3.connectionpool] [_make_request():396] https://someserver:443 \"GET /isam/capabilities/v1 HTTP/1.1\" 200 None\n[2018-01-26 17:22:16,459] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():63] Status Code: 200\n[2018-01-26 17:22:16,459] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():65] Text: [{\"name\":\"ISAM Base Appliance\",\"description\":\"IBM Security Access Manager Base Appliance\",\"id\":\"wga\",\"enabled\":\"True\"}, {\"name\":\"ISAM Advanced Access Control\",\"description\":\"IBM Security Access Manager Advanced Access Control\",\"id\":\"mga\",\"enabled\":\"True\"}, {\"name\":\"ISAM Federation\",\"description\":\"IBM Security Access Manager Federation\",\"id\":\"federation\",\"enabled\":\"True\"}]\n[2018-01-26 17:22:16,460] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_response():579] Response: 0\n[2018-01-26 17:22:16,460] [PID:56043 TID:139764347021120] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieve the cluster signature file ***\n[2018-01-26 17:22:16,460] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():92] Checking for minimum version: None.\n[2018-01-26 17:22:16,461] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():108] Checking for one of required modules: None.\n[2018-01-26 17:22:16,461] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():125] Warnings: []\n[2018-01-26 17:22:16,461] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [invoke_get_file():242] Headers are: {'Accept': 'application/json,application/octet-stream'}\n[2018-01-26 17:22:16,461] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():35] Suppressing SSL Warnings.\n[2018-01-26 17:22:16,461] [PID:56043 TID:139764347021120] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():24] Issuing request to: https://someserver:443/isam/cluster/signature/v1\n[2018-01-26 17:22:16,462] [PID:56043 TID:139764347021120] [DEBUG] [urllib3.connectionpool] [_new_conn():824] Starting new HTTPS connection (1): someserver\n[2018-01-26 17:22:16,933] [PID:56043 TID:139764347021120] [DEBUG] [urllib3.connectionpool] [_make_request():396] https://someserver:443 \"GET /isam/cluster/signature/v1 HTTP/1.1\" 500 None\n[2018-01-26 17:22:16,935] [PID:56043 TID:139764347021120] [ERROR] [ibmsecurity.appliance.ibmappliance] [invoke_get_file():251]   Request failed: \n[2018-01-26 17:22:16,935] [PID:56043 TID:139764347021120] [ERROR] [ibmsecurity.appliance.ibmappliance] [invoke_get_file():252]      status code: 500\n[2018-01-26 17:22:16,936] [PID:56043 TID:139764347021120] [ERROR] [ibmsecurity.appliance.ibmappliance] [invoke_get_file():254]      text: {\"message\":\"Error: WGAWA0389E   A cluster must be defined before this request can be processed.  To define a cluster the primary master must be set to something other than 127.0.0.1.\"}\n", "msg": "('HTTP Return code: 500', u'{\"message\":\"Error: WGAWA0389E   A cluster must be defined before this request can be processed.  To define a cluster the primary master must be set to something other than 127.0.0.1.\"}')", "name": "ibmsecurity.isam.base.cluster.signature.export"}
> 
> 
> TASK [export_cluster_sign : Export cluster signature from Primary appliance] *******************************************************************************************
> fatal: [someserver]: FAILED! => {"changed": false, "failed": true, "log": 

As one can know, it is premature to invoke the role 'export_cluster_sign' (or any other role of that sort) if the previous cluster changes are not commited.

Going up a bit the stack of message, we can clearly see that roles that executed (config_policyserver, set_cluster_config) did raise the status "changed", but the flushing the handlers did not help as their execution was skipped:

> RUNNING HANDLER [start_config : Commit Changes] ************************************************************************************************************************
> skipping: [someserver]
> 
> RUNNING HANDLER [start_config : Restart Web Runtime] *******************************************************************************************************************
> skipping: [someserver]

So I think we can narrow our investiguation as to why the handlers (Commit Changes and Restart Web Runtime) are skipped.

What happens after this point is irrelevant as until changes are commited and Web Runtime recycled, other task/play are very likely to fail.

As far as I recalled, when we were using the "master" branch of ibmsecurity, this behavior did not show up on 9.04 for that particular sequence of roles.

**Comment by ram-ibm** [comment]
I read this a few times to make sure I understood - the part I am not following is the last paragraph:

"As far as I recalled, when we were using the "master" branch of ibmsecurity, this behavior did not show up on 9.04 for that particular sequence of roles."

Could you explain this more please? So the commit is not working for the "lab" branch of or v9.0.4 or a combination?

**Comment by sygilber** [comment]
Over the past days, i reproduced the issue with combination of lab branch and isam 9.0.4. The difference this time is that i have performed all steps (roles) from a fresh set of appliances where each role had to execute. 

Let me know if you need more details.

**Comment by ram-ibm** [comment]
My initial thought is that the trace you pasted above is not executing ibmsecurity code when it comes to the commit. If you hit ibmsecurity code for commit then the ansible status would show as either "changed" or "ok" - this is showing "skipped". So Ansible is making the determination that commit handler does not need to be called and is not invoking ibmsecurity code.

What version of Ansible is this? Also relevant maybe the Ansible configuration file you are using to run this. Have you run this with -vvv to see why the handlers are getting skipped please?

**Comment by sygilber** [comment]
Closing this issue for now.

Will see if in our next build of ISAM this issue will resurface.

**Comment by sygilber** [comment]
Re-opening issue as we are building fresh new 9.0.5 Appliances and getting same issue as before. This time I will try to go at the botton of the issue.

**Comment by sygilber** [comment]
Leaving a bit of information here since I resumed investiguation on this issue.

I happend to remove all non-essential roles invocation and only preserve those that are truely required to reproduce consistently and systematically the behavior (commit handler after inactivity timeout update() in config_policyserver is skipped):

```
    - role: set_ldap_root_pw
      when: config_policyserver_user_registry == "local" and config_policyserver_ldap_pwd != ""
    - role: config_policyserver
```

If I remove the first role in the play (set_ldap_root_pw) and only preserve what's next then the commit handler is not skipped:

`   - role: config_policyserver`

I still have no clue why but I will continue to drill down.


```
ansible --version
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/userhome/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

**Comment by sygilber** [comment]
So far, as a work around to the above behavior, I have found that I could call set_ldap_root_pw from a different Play than the Play that contains the call to the config_policyserver role, and now all works fine: The Commit handler for the role config_policyserver is not skipped anymore.

Although the root cause of this behavior is not yet identified, it is good enough for us, for now, until I have more time (or others) to continue this investigation.

**Comment by ram-ibm** [comment]
Configuring policy server does not require a commit. This applies to execution of pdadmin commands as well. Is it possible that was the issue? Keeping this open to understand more.

**Comment by sygilber** [comment]
Ram, I know that I should always trust whatever you say about ISAM but allow me to have been destabilize by your previous remark: `Configuring policy server does not require a commit` so I went and did my little experiment which is found in the attachment provided.

And yes, configuring the Policy Server does not trigger any 'commit'. This is fascinating! I don't think I had ever configured manually via the LMI a Policy Server in the last 2 years !

[issues-56-capture.pdf](https://github.com/IBM-Security/ibmsecurity/files/2984806/issues-56-capture.pdf)

As I said previously, I have circumvented this behavior by leaving the config_policyserver role invocation isolated in its own Ansible play, and no longer we are having the handler skipping messages. 

So what you are saying is that it is very possible for the config_policyserver role role to flush any previous "commit" flags previously reported by prior roles that executed. If so, is there a way to "code" in ibmsecurity stack that the sole fact of invocating the role config_policyserver should not flush the previous "commit" state ?

**Comment by ram-ibm** [comment]
I typically use the "meta: flush_handlers" option to clear any commits needed before hand:
https://docs.ansible.com/ansible/latest/modules/meta_module.html

You will see this in some of the roles to ensure there are no pending changes before a particular change is processed. Not sure if that is what you are looking for?

I think it is a very successful implementation if you are no longer using the LMI 😀

**Comment by sygilber** [comment]
Ram, would you think that inserting the "meta: flush_handlers" directive inside the role execution right at the beginning would benefit those we are not aware of the behavior of the Policy Server initial configuration behavior (no commit detected) ?  The other option of course would be to insert this directive in an Ansible play right before running the config_policyserver role, that would do the job most probably but would leave ansible playbook developer in the dark, not knowing they must to this, unless it is documented in the readme that comes with the role.

**Comment by ram-ibm** [comment]
Yes I agree - we may need to flush handlers before configuring policy server AND reverse policy.

**Comment by ram-ibm** [comment]
Can we close this please?

**Comment by sygilber** [comment]
Closing this issue. Resolution is awaiting in the isam-ansible-roles repo (see previous comment above)
