### ISSUE TITLE
OIDC Connect Provider (9.04)

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/ibmsecurity#58]
Just logging out the fact that I could not locate in the ibmsecurity code yet support for the 9.04's OIDC Connect Provider additionnal parameters in the AAC API Definition. I can still use the existing ansible role 'add_oauth_definition' to implement most of our requirements, and complete the OIDC Connect Provider parameter in some other ways (manual or direct rest-api).

I understand that there will be logic necessary to detect the appliance version and thus only process the OIDC parameter should it be 9.04 appliance.

I don't exclude seeing if I could propose an implementation if it is not in the short term plans to provide support for it. Maybe code is already implemented but simply not published yet. Please let us know how we could help on this one.

**Comment by ram-ibm** [comment]
Sylvain - I will be merging the lab branch to the master pretty soon. Once that is done, then I am looking to make more changes. Further changes will go after that merge is made.

The key utility is how version comparisons will be made going forward - there is a utility function to do that. The current string based comparison is not very robust.

I appreciate any help I can get to make get changes made for 9.0.4 compatibility!

**Comment by ram-ibm** [comment]
master has the been merged.

**Comment by ram-ibm** [comment]
This is implemented - I will push code changes soon.
