### ISSUE TITLE
get https port URL

### ISSUE THREAD

**Issue by Imran-ibm** [IBM-Security/ibmsecurity#6]
For ISAM 9 (atleast) the URL to get the next https port is 

/isam/wga_templates/httpsport?ip_addr=

Not:

`def get_next_https_port(isamAppliance, ip_address, check_mode=False, force=False):
    """
    Find the next available HTTPS port for an interface
    """
    return isamAppliance.invoke_get("Find the next available HTTPS port for an interface",
                                    "/isam/wga_templates/httpsport/{0}".format(ip_address))`

Thanks

**Comment by ram-ibm** [comment]
It seems to have changed with v9.0.2.0. I will update when I add the code to handle it. The framework can handle versions - unfortunately, there is no reliable way to figure out changes between versions so need to handle it on a case by case basis.

**Comment by ram-ibm** [comment]
Code was posted to handle the change from v9.0.2.0.

**Comment by ram-ibm** [comment]
I fixed the version to be v8 when we need to pass query parameter. Code is now published.
