### ISSUE TITLE
 "msg": "Error> action does not have the right set of arguments or there is a code bug! Options: 

### ISSUE THREAD

**Issue by ramraj241** [IBM-Security/ibmsecurity#60]
So one of our junction create yml process which use to work  until recently stopped working with this error "msg": "Error> action does not have the right set of arguments or there is a code bug! Options: , We are using ansible 2.3.1.0 and python version 2.7.10, we are passing all the required arguments to the yml file .any help on this is appreciated.

**Comment by sygilber** [comment]
Hi. can show which attributes get passed onto the junction ? Have you refreshed lately with the master branch of ibmsecurity and the roles, and/or have you updated your appliance firmware lately ?

**Comment by ramraj241** [comment]
here is the yml file 

- name: junction create
  hosts: all
  connection: local
  roles:
    - role: add_junction
      tags: ["reverseproxy", "junction", "add"]
      add_junction_reverseproxy_id: "{{ da_name }}"
      add_junction_junction_point: "{{ jct_name}}"
      add_junction_junction_type: "{{ jct_type }}"
      add_junction_server_hostname: "{{ jct_hostname }}"
      add_junction_server_port: "{{ jct_port }}"
      add_junction_transparent_path_junction: "{{ jct_transparent }}"
      add_junction_stateful_junction: "{{ jct_stateful }}"
    - role: execute_pdadmin
      tags: ["pdadmin", "object", "acl"]
      execute_pdadmin_commands:
        - "acl attach /WebSEAL/{{ inventory_hostname }}-{{ da_name }}{{ jct_name}} {{ acl }}"
      execute_pdadmin_isamuser: "{{sec_master_id}}"
      execute_pdadmin_isampwd:  "{{sec_master_pwd}}"
      execute_pdadmin_domain:  "Default"

Here is the command we execute
/usr/local/bin/ansible-playbook -i @inventories/0-DFLT @general/junction_create.yml -l ***.com -e "inventory_hostname=***.com da_name=***  jct_name=/tessting jct_type=ssl jct_hostname=***.com jct_port=443 jct_transparent=yes jct_stateful=yes acl=unauth sec_master_id=****  sec_master_pwd=****  force=true" --vault-password-file=~/.vault_pass.secret | sed 's/\\n/\n/g'

yes i did clone with latest roles today and tried again, same error
 "msg": "Error> action does not have the right set of arguments or there is a code bug! Options: isamAppliance=isam_server, force=True, server_hostname=\"***.com\", junction_point=\"/tessting\", proxy_hostname=None, key_label=None, https_port=None, delegation_support=None, query_contents=None, gso_resource_group=None, server_uuid=None, cookie_include_path=None, fsso_config_file=None, ltpa_keyfile_password=None, sms_environment=None, http_port=None, windows_style_url=None, authz_rules=None, junction_soft_limit=\"90\", case_sensitive_url=None, tfim_sso=None, junction_type=\"ssl\", server_port=\"443\", insert_session_cookies=None, username=None, remote_http_header=['iv-user', 'iv-user-l', 'iv-groups'], ltpa_keyfile=None, enable_basic_auth=None, junction_hard_limit=\"95\", mutual_auth=None, stateful_junction=\"yes\", proxy_port=None, password=None, virtual_hostname=None, insert_ltpa_cookies=None, junction_cookie_javascript_block=None, local_ip=None, client_ip_http=\"yes\", version_two_cookies=None, scripting_support=None, vhost_label=None, reverseproxy_id=\"mycigna_mobile_2\", basic_auth_mode=None, request_encoding=\"utf8_bin\", preserve_cookie=None, transparent_path_junction=\"yes\", server_dn=None",
    "name": "ibmsecurity.isam.web.reverse_proxy.junctions.add"

**Comment by sygilber** [comment]
I have seen similar issue just couple months ago when there had been rename of some parameter in python module and the roles module had to be adjusted just after otherwise this error occured. But before going any further in this direction and asking for more logs (-vvv), is it possible to confirm which ibmsecurity module version that you are using ?

**Comment by ramraj241** [comment]
/usr/local/bin/ansible-playbook -i @inventories/0-DFLT @general/junction_create.yml -l ***.com -e "inventory_hostname=***.com da_name=*** jct_name=/tessting jct_type=ssl jct_hostname=***.com jct_port=*** jct_transparent=yes jct_stateful=yes acl=unauth sec_master_id=*** sec_master_pwd=****  force=true" -vvv --vault-password-file=~/.vault_pass.secret | sed 's/\\n/\n/g'
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: junction_create.yml ***************************************************************************************************************************************************************************************************************
1 plays in @general/junction_create.yml

PLAY [junction create] **********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/system/setup.py
<***.com> ESTABLISH LOCAL CONNECTION FOR USER: devops
<***.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<***.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/devops/.ansible/tmp/ansible-tmp-1519183974.97-230504817606933 `" && echo ansible-tmp-1519183974.97-230504817606933="` echo /home/devops/.ansible/tmp/ansible-tmp-1519183974.97-230504817606933 `" ) && sleep 0'
<***.com> PUT /tmp/tmpCwZvUM TO /home/devops/.ansible/tmp/ansible-tmp-1519183974.97-230504817606933/setup.py
<***.com> EXEC /bin/sh -c 'chmod u+x /home/devops/.ansible/tmp/ansible-tmp-1519183974.97-230504817606933/ /home/devops/.ansible/tmp/ansible-tmp-1519183974.97-230504817606933/setup.py && sleep 0'
<***.com> EXEC /bin/sh -c '/usr/local/Python-2.7.10/python /home/devops/.ansible/tmp/ansible-tmp-1519183974.97-230504817606933/setup.py; rm -rf "/home/devops/.ansible/tmp/ansible-tmp-1519183974.97-230504817606933/" > /dev/null 2>&1 && sleep 0'
ok: [***.com]
META: ran handlers
META: noop

TASK [add_junction : Add a Junction - /tessting] ********************************************************************************************************************************************************************************************
task path: /CIGNA/ansible-controller/isam-ansible-roles/add_junction/tasks/main.yml:1
Using module file /CIGNA/ansible-controller/isam-ansible-roles/start_config/library/isam.py
<***.com> ESTABLISH LOCAL CONNECTION FOR USER: devops
<***.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<***.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/devops/.ansible/tmp/ansible-tmp-1519183976.33-27891409833847 `" && echo ansible-tmp-1519183976.33-27891409833847="` echo /home/devops/.ansible/tmp/ansible-tmp-1519183976.33-27891409833847 `" ) && sleep 0'
<***.com> PUT /tmp/tmpP2yVls TO /home/devops/.ansible/tmp/ansible-tmp-1519183976.33-27891409833847/isam.py
<***.com> EXEC /bin/sh -c 'chmod u+x /home/devops/.ansible/tmp/ansible-tmp-1519183976.33-27891409833847/ /home/devops/.ansible/tmp/ansible-tmp-1519183976.33-27891409833847/isam.py && sleep 0'
<***.com> EXEC /bin/sh -c '/usr/local/Python-2.7.10/python /home/devops/.ansible/tmp/ansible-tmp-1519183976.33-27891409833847/isam.py; rm -rf "/home/devops/.ansible/tmp/ansible-tmp-1519183976.33-27891409833847/" > /dev/null 2>&1 && sleep 0'
 [WARNING]: Module did not set no_log for password
fatal: [***.com]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "action": "ibmsecurity.isam.web.reverse_proxy.junctions.add",
            "appliance": "***.com",
            "force": true,
            "isamapi": {
                "authz_rules": null,
                "basic_auth_mode": null,
                "case_sensitive_url": null,
                "client_ip_http": "yes",
                "cookie_include_path": null,
                "delegation_support": null,
                "enable_basic_auth": null,
                "fsso_config_file": null,
                "gso_resource_group": null,
                "http_port": null,
                "https_port": null,
                "insert_ltpa_cookies": null,
                "insert_session_cookies": null,
                "junction_cookie_javascript_block": null,
                "junction_hard_limit": "95",
                "junction_point": "/tessting",
                "junction_soft_limit": "90",
                "junction_type": "ssl",
                "key_label": null,
                "local_ip": null,
                "ltpa_keyfile": null,
                "ltpa_keyfile_password": null,
                "mutual_auth": null,
                "password": null,
                "preserve_cookie": null,
                "proxy_hostname": null,
                "proxy_port": null,
                "query_contents": null,
                "remote_http_header": [
                    "iv-user",
                    "iv-user-l",
                    "iv-groups"
                ],
                "request_encoding": "utf8_bin",
                "reverseproxy_id": "mycigna_mobile_2",
                "scripting_support": null,
                "server_dn": null,
                "server_hostname": "v-tltinternal.cigna.com",
                "server_port": "443",
                "server_uuid": null,
                "sms_environment": null,
                "stateful_junction": "yes",
                "tfim_sso": null,
                "transparent_path_junction": "yes",
                "username": null,
                "version_two_cookies": null,
                "vhost_label": null,
                "virtual_hostname": null,
                "windows_style_url": null
            },
            "lmi_port": 443,
            "log": "INFO",
            "password": "admin2",
            "username": "admin"
        }
    },
    "log": "[2018-02-20 22:32:56,576] [PID:5731 TID:140554840160000] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():29] *** Retrieving firmware ***
[2018-02-20 22:32:57,258] [PID:5731 TID:140554840160000] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():29] *** Get Setup Complete Settings ***
[2018-02-20 22:32:57,639] [PID:5731 TID:140554840160000] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():29] *** Retrieving activations ***
",
    "msg": "Error> action does not have the right set of arguments or there is a code bug! Options: isamAppliance=isam_server, force=True, server_hostname=\"***.com\", junction_point=\"/tessting\", proxy_hostname=None, key_label=None, https_port=None, delegation_support=None, query_contents=None, gso_resource_group=None, server_uuid=None, cookie_include_path=None, fsso_config_file=None, ltpa_keyfile_password=None, sms_environment=None, http_port=None, windows_style_url=None, authz_rules=None, junction_soft_limit=\"90\", case_sensitive_url=None, tfim_sso=None, junction_type=\"ssl\", server_port=\"443\", insert_session_cookies=None, username=None, remote_http_header=['iv-user', 'iv-user-l', 'iv-groups'], ltpa_keyfile=None, enable_basic_auth=None, junction_hard_limit=\"95\", mutual_auth=None, stateful_junction=\"yes\", proxy_port=None, password=None, virtual_hostname=None, insert_ltpa_cookies=None, junction_cookie_javascript_block=None, local_ip=None, client_ip_http=\"yes\", version_two_cookies=None, scripting_support=None, vhost_label=None, reverseproxy_id=\"mycigna_mobile_2\", basic_auth_mode=None, request_encoding=\"utf8_bin\", preserve_cookie=None, transparent_path_junction=\"yes\", server_dn=None",
    "name": "ibmsecurity.isam.web.reverse_proxy.junctions.add"
}
        to retry, use: --limit @/opt/scm/udeploy/agent/var/work/wd.atm.1.webseal-devops-tar/wd.atm.1.webseal-devops-tar/scripts/isam9_ansible/@general/junction_create.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
***.com : ok=1    changed=0    unreachable=0    failed=1

**Comment by ram-ibm** [comment]
Since you refreshed your roles - you may need to refresh your ibmsecurity python package as well. We recently fixed the "server_uid" variable to be server_uuid. Your Ansible role and python package are out of sync.

**Comment by ramraj241** [comment]
thanks, code refresh did the trick

**Comment by ram-ibm** [comment]
Thanks for the update.
