### ISSUE TITLE
Ansible fails to merge different variable formats required by roles

### ISSUE THREAD

**Issue by owla101** [IBM-Security/ibmsecurity#61]
Hi, I've been working on defining an inventory structure in which I store instance and junction vars that are specific to a host in a given environment under a folder structure within host_vars.  The below tree shows the an excerpt of the structure for a dev environment:-

├├── inventories
│   ├── dev
│   │   ├── group_vars
│   │   │   ├── all
│   │   │   │   ├── vars.yml
│   │   │   │   └── vault.yml
│   │   │
│   │   │   ├── reverseproxies
│   │   │   │   └── vars.yml
│   │   │   └── site.yml
│   │   ├── hosts
│   │   └── host_vars
│   │       ├── myhost1
│   │       │   └── reverseproxy_vars
│   │       │       ├── junction_vars
│   │       │       │   └── groovyRP
│   │       │       ├── reverse_proxy_cfg_vars
│   │       │       │   └── groovyRP_vars.yml
│   │       │       └── vault.yml
│   │       └── myhost2
│   │           └── reverseproxy_vars
│   │               ├── junction_vars
│   │               │   └── groovyRP
│   │               ├── reverse_proxy_cfg_vars
│   │               │   └── groovyRP_vars.yml
│   │               └── vault.yml

I'm pulling the instance variables into the playbook using a path in vars_files.  The idea is to define a structure that can be version controlled in Git and allow for changes to be isolated to the file relating to the instance / junction be changed.  I also want to externalize the variables from the playbooks themselves so that the same playbooks can be used to deploy changes to any environment.

This was working fine until I introduced the set_junction into the mix.  When I added a vars file for this into my inventory (groovy_jct) I started to get the following error:-

ERROR! failed to combine variables, expected dicts but got a 'dict' and a 'AnsibleSequence':
{}
[{"set_junction_junction_point": "/groovy_jct"}, {"set_junction_junction_type": "ssl"}, {"set_junction_reverseproxy_id": "groovyRP"}

It would appear that Ansible can't merge the inventory files as the variables for the update_reverseproxy is an array and the set_junction variables are key value pairs.

I'm wondering if anyone else has hit this issue or have had other ideas around building out the Ansible inventory for storing ISAM variables.

If this question isn't valid for this forum could you advise if there's a better place for it.  It would be great to be able to discuss and share experiences on the build out of the ISAM inventory and related version control matters.

**Comment by sygilber** [comment]
Hi. We have invested lots of time in the past months elaborating a devops stack for isam using git,  a linux node of course, one for each of our staging area (intg,uat,preprod,prod) to simplify things as far as scoping safely playbook runs is concerned. We have pretty much success for building our appliances with that. At the beginning we used a single git ´local’ repo for all things concerned with ansible but we evolve it to using a multi-repo approach to segment/isolate playbooks, roles, inventories, and more sensitive data. A more modular building block approach where playbook, roles dont know where the other modules are located, and for which references to each other are resolved at runtime using environment variables. 

Then came our experience of setting up our junctions from git and automating that to be an unattended process. We came across similar issue for the set-junction role. We have not yet identified a perfect solution for now. But we decides to evolve our platform in slow-iterative approach. Git allows us that now. Just imagine that we were using centralized scripts for the past 10 years centrally located in a share nfs file system. Once working, no one wanted touch them concerned of breaking the thing. 

For now, we are using a playbook that imports a single yml file in the vars section i believe (have to check this back) that contains all junctions definition for a particular reverse proxy cluster. We add a junction there when required and rerun the playbook for this entire reverse proxy. Theorically this should not be a concerned given ansible idempotency but actually we are facing now minor issue with it (idempotency) but we are confident that we could resolve this with a bit of more digging in the next couple weeks. 

Do we want a better approach ? We were hopping to head for a single yml file definition approach for each junction but then if we do that we need consider looping through all the junction file individually but we could opt with this approach to run set_junction to only the new files extracted from git, for performance reason. 

Ansible can be quite slow with all checks it must performed at runtime. Not sure if we add more CPU on our linux VM if it will speed this up, or if this is more a bottleneck on the transport side (individual restcalls) for each junction listed in a playbook. 

Going back at our single yml file: we do need to have a uniform list of jct parameter defined in our single yml file per proxy approach. When we evolve to a one jct file approach per junction, it will allow us to only set the jct parameter for that particular junction as opposed of being forced to define all of them. 

Our idea is to evolve our solution gradually, learn from observations, tune it a bit further, repeat.  

Sorry for having gone somewhat overboard with my comment; i just found that you hit exactly where we are now in of evolution/transformation to isam/git tool chain. 

Sylvain

**Comment by owla101** [comment]
Hi Sylvain,

It good to hear that others are working through similar challenges :-)  

I have also defied a multi repo model for roles, playbooks and each environment in the inventory.  Given that the ISAM variables are different in each environment I didn't see the benefit of having one overarching repo for all environments in the inventory (thought still possible I'm missing something here!

I've got the instances deployments working nicely with a separate yml file holding the specific variables for each instance.  My playbook for this creates a default instance then runs the update_reverse proxy roles to use a vars_file to update that default with instance specific config....all good.  Set junction was also working fine until I moved from using the default hosts file to a host file in the inventory.............then above error.

I get what your saying about migrating 10 years of TAM / ISAM config to a new format for using with the Ansible playbooks.  Its a big overhead and would mean everything being redeployed / retested.  Maybe a hard sell to those that pay for projects.  But having said that I think its definitely where we should be heading.

For me being able to isolate the change to particular instance or junction yml file and to be able to just deploy that change only is the ideal situation.  

Paul

**Comment by sygilber** [comment]
A clarification: I realised this morning now that we have our own version of the existing 'set_junction' role that iterates over each junction defined in our per-proxy yml file.

After our next deliverbale in prod soon, we will start thinking back how we want to refine how to creation junction in an efficient way.  Maybe then we can have this discussion back.

**Comment by ram-ibm** [comment]
I sense the following topics needing to be addressed:
1. Organizing Playbooks, Roles and Variables
2. git structure (or whatever release control system being used)
3. Use of "tags" to allow for specific tasks to be executed

**Comment by owla101** [comment]
Hey Ram, yeah! it would be grate to cover those items above and have somewhere where experiences  / best practice could be shared.

**Comment by ram-ibm** [comment]
I think it is a very personal choice as to where you maintain your dynamic data. It is possible to define a junction role that does all junction creates and simply feed it a data structure for all junction you want to create. I prefer having playbooks organized based on business needs and only parameterize that which changes between environments. Currently I have separate set_junction for each junction that needs to be created and values that we know are true for all environments are hardcoded into it - e.g. is the junction tcp or ssl. In addition we execute pdadmin commands add extra servers and tie them as one atomic unit using "tags". This, to me, matches more closely with what the business demands and allows us to manage changes better.

**Comment by owla101** [comment]
..I like the idea of separating out the environment specific variables from the those that are the same across all environments Ram.  Given the playbooks could be in their own repository this wold result in one change to those variables that can then be version controlled in Git and deployed throughout all environments.   

Just wondering, do you do the same for reverse proxies, i.e. have a playbook for each with the environment variables in there that are the same across all environments?

**Comment by ram-ibm** [comment]
If you are going to be @ IBM Think - we can meet in person as well.

For reverse proxies:
1. Once single reverse proxy is all you need to leverage all the horsepower of an appliances - hence we have just one reverse proxy for all appliances. And they are all named the same.
2. Playbooks to configure functionality - i.e. tag value headers - are in a playbook and we use the same settings for all environments.
3. Non-functional settings are in a separate playbook - and since our appliances are sized the same we use the same settings everywhere.
4. Playbooks for creating junctions are created separate for each functional area we support. The junction themselves are set_junction roles with more values hardcoded except for that that vary between environments - backend server and port being the main ones. In some cases application chose to use tcp versus ssl junctions in lower environments.

**Comment by owla101** [comment]
Hey Ram IBM Think......no such luck for me I'm afraid :-)

To your first point above:-
_1. Once single reverse proxy is all you need to leverage all the horsepower of an appliances - hence we have just one reverse proxy for all appliances. And they are all named the same.__

....does that not lead to spread in the impact in terms of impacted business units if there needs to be a config change to the single reverse proxy or if it has to be restarted to take in a cert change for instance?

**Comment by ram-ibm** [comment]
What I meant is that we are avoiding having to create multiple reverse proxies on an appliance. If we need another reverse proxy - then we make sure to create a separate appliance for it as well. So if you need multiple reverse proxies for redundancy or whatever other reason - then they would be created one per appliance.

We always have multiple servers - so there is no impact during maintenance.
