### ISSUE TITLE
Can we add this function under ibmsecurity/isam/web/reverse_proxy/interfaces.py

### ISSUE THREAD

**Issue by Imran-ibm** [IBM-Security/ibmsecurity#7]
Could we have this added , this looks necessary to me :

**Use case : Get the listening_port from this output , which can be used to automate creation of reverse proxy instances (by getting the next available listening_port along with the https_port)**

`def get_default(isamAppliance, check_mode=False, force=False):`
    
    get_uri = "/isam/wga_templates/defaults"
    return isamAppliance.invoke_get("Get defaults", get_uri)`

example of my role which is working and setting a var from the output :

`- name: Get listening ports`
  `isam:`
   ` appliance: `
 `  username:  admin`
   ` password:  `
   ` lmi_port:  "{{ lmi_port }}"`
   ` force:     "{{ force }}"`
    `log:       "{{ log_level }}"`
    `action: ibmsecurity.isam.web.reverse_proxy.interfaces.get_default`
  `register: ret_obj_listening`

`- set_fact:`
   ` listening_port: "{{ ret_obj_listening['data']['listening_port'] }}"`

**Comment by ram-ibm** [comment]
Is this API docuemnted anywhere? I did not find it in the knowledge center. Was looking specifically for the description so I can plug it into the function.

**Comment by Imran-ibm** [comment]
I do not think it is documented yet, i remember (vaguely) getting this from the local ISAM team here at the goldcoast. 
Here is a sample o/p of the Rest Call :

`{`
  `"domain": "Default",`
  `"admin_id": "sec_master",`
  `"host": "ws1-local",`
  `"ssl_port": "636",`
  `"listening_port": "7235"`
`}`

**Comment by ram-ibm** [comment]
Added - it is called get_defaults to match the uri.
