### ISSUE TITLE
Idempotency issue with "remote_http_header" param for junction.set

### ISSUE THREAD

**Issue by LouBea** [IBM-Security/ibmsecurity#72]
Hi Ram,

As per the doc, for param "remote_http_header", the "all" option is supported. The junction is created accordingly.

But on a second run of the script the idempotency is not working, the jct is flagged as changed because in the "new" jct, the param show as "all":

```
...
('remote_http_header', 'all'), 
...
```

whereas in the existing  jct json, it is an array of explicit values that is returned:

```
...
('remote_http_header', ['iv_creds', 'iv_groups', 'iv_user']), 
...
```

Regards,
Louis

**Comment by ram-ibm** [comment]
I made the change - will test and push it out.

**Comment by LouBea** [comment]
Tested : this is fixed, many thanks.
