### ISSUE TITLE
Client API Protection - RFC 7636 support (9.0.4)

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/ibmsecurity#73]
Just logging out the fact that I could not locate in the ibmsecurity code yet support for the 9.04's RFC 7636 (Proof Key of Code Exchange) additionnal parameters in the AAC Oauth Client Definition. Probably some others new 9.0.4 parameters missing there also on the ibmsecurity.isam.aac.api_protection.client.py python module.

Version logic will be required to filter out those 9.0.4 params when the appliance is of version less than 9.0.4

Again, I don't exclude seeing if I could propose an implementation if it is not in the short term plans to provide support for it. Maybe code is already implemented but simply not published yet. Please let us know how we could help on this one. Sometime Ram is faster than we are are providing implementation for missing area. Still, I hope we can do some as well.  We are identying some of the new 9.0.4 Oauth features because we are making use pretty much of all of them in our new solutions.

Thanks

**Comment by ram-ibm** [comment]
I am working this - will submit code once I test it out.

**Comment by sygilber** [comment]
Resolve by https://github.com/IBM-Security/ibmsecurity/commit/e16208a3c6b03657c3ebf93c7e3c6048090e6367.

Thanks
