### ISSUE TITLE
Idempotency issue with remote_http_header attribute for custom role

### ISSUE THREAD

**Issue by LouBea** [IBM-Security/ibmsecurity#77]
For the attribute remote_http_header, I have a issue similar to issue #69

I need to pass an explicit default value through a jinja2 filter for this parameter (in cases where it is not specified because we do not want to include any HTTP Header Identity Information). 

What is slightly different is that I cannot use:

`remote_http_header: "{{ item.set_junction_remote_http_header | default(None) }}"`

because, as discussed in issue #69, this would pass an empty string and an empty string is not accepted, it gives me an error message.

I need to use 

`remote_http_header: "{{ item.set_junction_remote_http_header | default([]) }}"`

For this code to be idempotent, I would need junctions.py to be modified from:

```
if remote_http_header is None:
    jct_json['remote_http_header'] = 'do not insert'
elif isinstance(remote_http_header, basestring) and remote_http_header.lower() == 'all':
    jct_json['remote_http_header'] = ['iv_creds', 'iv_groups', 'iv_user']
else:
    jct_json['remote_http_header'] = remote_http_header
```

to

```
if remote_http_header is None or remote_http_header == []:
    jct_json['remote_http_header'] = 'do not insert'
elif isinstance(remote_http_header, basestring) and remote_http_header.lower() == 'all':
    jct_json['remote_http_header'] = ['iv_creds', 'iv_groups', 'iv_user']
else:
    jct_json['remote_http_header'] = remote_http_header
```

I will create a pull request for this correction.

Thanks
Louis

**Comment by ram-ibm** [comment]
I believe this is now fixed.
