### ISSUE TITLE
Parse fixpack file for idempotency

### ISSUE THREAD

**Issue by normanfield** [IBM-Security/ibmsecurity#9]
fixpack.py can only be truly idempotent if the name of the fixpack stored on the appliance is compared against the name of the fixpack stored in the fixpack binary.  The unix strings command can find it like:
```
$ strings 16890_122_000_9021_IPv6_Routes_Fix.fixpack | grep FIXPACK 
FIXPACK_ID="9021_IPv6_ROUTES_FIX" 
FIXPACK_NAME="9021_IPv6_Routes_fix"
FIXPACK_DESCRIPTION="This fixpack corrects a problem where the routes tab in LMI does not display properly after adding an IPv6 address to an interface." 
FIXPACK_FIRMWARE_VERSION="9.0.2.*1"
```
Ideally, this would be implemented using a Python API rather than a system call to string to make it platform independent.

**Comment by ram-ibm** [comment]
Many thanks for the strings() function. We now have better idempotency for fixpack installs.
