### ISSUE TITLE
Inconsistency in ISDS API documentation can cause an HTTP Error 500

### ISSUE THREAD

**Issue by Franclaf7** [IBM-Security/ibmsecurity#95]
Hi, I was working on adding a hostname to a host IP address on a ISDS Appliance and was getting an HTTP Error 500. Finally realized there was an inconsistency in the API documentation which was causing me to send the wrong parameters in my request body.

In the API doc, we can see the difference between the _Request Body_ and the _Request Example_:

**Request Body**
Name | Type | Optional | Description
hostname | String | No | The host name in the host record.

VS

**Request Example**
 POST https://{appliance_hostname}/host_records/{host_address}/hostnames

 POST_DATA:
 {
 "name":"The hostname to add"
 }
 
 GET https://{appliance_hostname}/host_records

I guess it's supposed to be **hostname** for both, but the API currently only accepts **name** as a parameter.

Once this is fixed in the API doc, I will make a new pull request with this function (add_hostname() in isds/host_records.py) and other additions.

Thanks,
Francis L.

**Comment by ram-ibm** [comment]
This might be best resolved by executing the command using the browser GUI and tracing the REST API call.

**Comment by Franclaf7** [comment]
I was able to fix the REST API call and make it work. With the API set up the way it is, "name" is the parameter to use in a call, so i guess it's the "Request Body" (hostname) doc that would need to be changed.

I will make a new pull request.

Thanks

**Comment by Franclaf7** [comment]
Issue is reported, going to close issue.
